#!/bin/bash
# D1.1 ROS2 CI-pending verification script
# Runs inside mass-l3/ci:jazzy-ubuntu22.04 container
# Verifies: colcon build exit 0 + mock publisher Hz + schema_version in topics
set -eo pipefail

WORKSPACE=/workspace
EVIDENCE_DIR="${WORKSPACE}/docs/Design/Detailed Design/D1.1-ros2-workspace/evidence"

echo "=== D1.1 ROS2 Verification ==="
echo "Date: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
echo "ROS_DISTRO: ${ROS_DISTRO:-unknown}"
echo ""

# Step 1: Install geographic_msgs + fix empy version conflict (R1.1 risk)
echo "--- Step 1: Install deps, fix empy conflict ---"
apt-get update -qq
apt-get install -y --no-install-recommends ros-jazzy-geographic-msgs python3-empy
# pip empy 4.x breaks rosidl_generator_rs which expects empy 3.x API
pip3 install --break-system-packages --quiet "empy==3.3.4"
source /opt/ros/jazzy/setup.bash
ros2 pkg list | grep geographic_msgs && echo "geographic_msgs: OK"

# Step 2: colcon build l3_msgs + l3_external_msgs
echo ""
echo "--- Step 2: colcon build ---"
cd "${WORKSPACE}"
colcon build --packages-select l3_msgs l3_external_msgs 2>&1 | tee /tmp/colcon_msgs.log
BUILD_EXIT=${PIPESTATUS[0]}
echo "colcon build exit: ${BUILD_EXIT}"

if [ "${BUILD_EXIT}" -ne 0 ]; then
  echo "ERROR: colcon build failed" >&2
  exit 1
fi

# Check no warnings
WARNING_COUNT=$(grep -ic "warning" /tmp/colcon_msgs.log || true)
echo "Warning lines in build log: ${WARNING_COUNT}"

# Step 3: Build mock publisher
echo ""
echo "--- Step 3: Build mock publisher ---"
source install/setup.bash
colcon build --packages-select l3_external_mock_publisher 2>&1 | tee /tmp/colcon_mock.log
MOCK_EXIT=${PIPESTATUS[0]}
echo "mock publisher build exit: ${MOCK_EXIT}"

# Re-source after second build
source "${WORKSPACE}/install/setup.bash"

# Debug: verify package is found
echo ""
echo "--- Package verification ---"
ros2 pkg list | grep l3_external_mock_publisher || echo "WARN: package not in ros2 pkg list"
echo "AMENT_PREFIX_PATH prefix count: $(echo $AMENT_PREFIX_PATH | tr ':' '\n' | wc -l)"

# Step 4: Run mock publisher + Hz verification
echo ""
echo "--- Step 4: Mock publisher Hz verification ---"

# Set up ROS2 environment for intra-container comms
export ROS_LOCALHOST_ONLY=1
ros2 daemon start 2>/dev/null || true
sleep 1

# Add installed site-packages to PYTHONPATH
SITE_PKGS="${WORKSPACE}/install/l3_external_mock_publisher/lib/python3.12/site-packages"
export PYTHONPATH="${SITE_PKGS}:${PYTHONPATH:-}"

# Also ensure l3 message packages are on PYTHONPATH
for pkg in l3_msgs l3_external_msgs; do
  PKGS_SITE="${WORKSPACE}/install/${pkg}/lib/python3.12/site-packages"
  [ -d "${PKGS_SITE}" ] && export PYTHONPATH="${PKGS_SITE}:${PYTHONPATH}"
done

# Run mock publisher directly with Python (console_scripts not generated by ament_python)
python3 -c "
from l3_external_mock_publisher.external_mock_publisher import main
import sys, os
sys.argv = ['external_mock_publisher']
main()
" > /tmp/mock_startup.log 2>&1 &
MOCK_PID=$!
echo "Mock publisher PID: ${MOCK_PID}"
sleep 5

# Check it's still running
if ! kill -0 "${MOCK_PID}" 2>/dev/null; then
  echo "ERROR: mock publisher crashed. Log:"
  cat /tmp/mock_startup.log
  exit 1
fi
echo "Mock publisher running OK"
head -5 /tmp/mock_startup.log || true
echo "Mock publisher PID: ${MOCK_PID}"
sleep 4  # warm up

# Verify 50 Hz
echo ""
echo "--- /fusion/own_ship_state Hz (expect ~50) ---"
timeout 15 ros2 topic hz /fusion/own_ship_state 2>&1 | tee /tmp/hz_50.log || true
grep "average rate" /tmp/hz_50.log | tail -1

# Verify 2 Hz
echo ""
echo "--- /fusion/tracked_targets Hz (expect ~2) ---"
timeout 10 ros2 topic hz /fusion/tracked_targets 2>&1 | tee /tmp/hz_2.log || true
grep "average rate" /tmp/hz_2.log | tail -1

# Verify 1 Hz
echo ""
echo "--- /l1/voyage_task Hz (expect ~1) ---"
timeout 10 ros2 topic hz /l1/voyage_task 2>&1 | tee /tmp/hz_1.log || true
grep "average rate" /tmp/hz_1.log | tail -1

# Verify schema_version in published message
echo ""
echo "--- schema_version in topic echo ---"
ros2 topic echo /fusion/own_ship_state --once 2>/dev/null | grep schema_version || echo "WARN: schema_version not found in echo"
ros2 topic echo /l1/voyage_task --once 2>/dev/null | grep schema_version || echo "WARN: schema_version not found in echo"

# Stop mock publisher
kill "${MOCK_PID}" 2>/dev/null || true
wait "${MOCK_PID}" 2>/dev/null || true

# Step 5: Save evidence
echo ""
echo "--- Step 5: Save evidence ---"
mkdir -p "${EVIDENCE_DIR}"
cp /tmp/colcon_msgs.log "${EVIDENCE_DIR}/colcon-build-ok.log"
cp /tmp/hz_50.log "${EVIDENCE_DIR}/hz-50-own-ship-state.log"
cp /tmp/hz_2.log "${EVIDENCE_DIR}/hz-2-tracked-targets.log"
cp /tmp/hz_1.log "${EVIDENCE_DIR}/hz-1-voyage-task.log"

# Summary
echo ""
echo "=== VERIFICATION SUMMARY ==="
echo "colcon build exit: ${BUILD_EXIT}"
echo "mock build exit:   ${MOCK_EXIT}"
echo "50 Hz evidence:    ${EVIDENCE_DIR}/hz-50-own-ship-state.log"
echo "colcon log:        ${EVIDENCE_DIR}/colcon-build-ok.log"
echo "All evidence saved to: ${EVIDENCE_DIR}"
