// @generated by protobuf-ts 2.11.1 with parameter generate_dependencies
// @generated from protobuf file "sil/ais_message.proto" (package "sil", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message sil.AISMessage
 */
export interface AISMessage {
    /**
     * @generated from protobuf field: uint32 mmsi = 1
     */
    mmsi: number;
    /**
     * @generated from protobuf field: double sog = 2
     */
    sog: number;
    /**
     * @generated from protobuf field: double cog = 3
     */
    cog: number;
    /**
     * @generated from protobuf field: double lat = 4
     */
    lat: number;
    /**
     * @generated from protobuf field: double lon = 5
     */
    lon: number;
    /**
     * @generated from protobuf field: double heading = 6
     */
    heading: number;
    /**
     * @generated from protobuf field: bool dropout_flag = 7
     */
    dropoutFlag: boolean;
}
// @generated message type with reflection information, may provide speed optimized methods
class AISMessage$Type extends MessageType<AISMessage> {
    constructor() {
        super("sil.AISMessage", [
            { no: 1, name: "mmsi", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "sog", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 3, name: "cog", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 4, name: "lat", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 5, name: "lon", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 6, name: "heading", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 7, name: "dropout_flag", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<AISMessage>): AISMessage {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.mmsi = 0;
        message.sog = 0;
        message.cog = 0;
        message.lat = 0;
        message.lon = 0;
        message.heading = 0;
        message.dropoutFlag = false;
        if (value !== undefined)
            reflectionMergePartial<AISMessage>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AISMessage): AISMessage {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint32 mmsi */ 1:
                    message.mmsi = reader.uint32();
                    break;
                case /* double sog */ 2:
                    message.sog = reader.double();
                    break;
                case /* double cog */ 3:
                    message.cog = reader.double();
                    break;
                case /* double lat */ 4:
                    message.lat = reader.double();
                    break;
                case /* double lon */ 5:
                    message.lon = reader.double();
                    break;
                case /* double heading */ 6:
                    message.heading = reader.double();
                    break;
                case /* bool dropout_flag */ 7:
                    message.dropoutFlag = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AISMessage, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint32 mmsi = 1; */
        if (message.mmsi !== 0)
            writer.tag(1, WireType.Varint).uint32(message.mmsi);
        /* double sog = 2; */
        if (message.sog !== 0)
            writer.tag(2, WireType.Bit64).double(message.sog);
        /* double cog = 3; */
        if (message.cog !== 0)
            writer.tag(3, WireType.Bit64).double(message.cog);
        /* double lat = 4; */
        if (message.lat !== 0)
            writer.tag(4, WireType.Bit64).double(message.lat);
        /* double lon = 5; */
        if (message.lon !== 0)
            writer.tag(5, WireType.Bit64).double(message.lon);
        /* double heading = 6; */
        if (message.heading !== 0)
            writer.tag(6, WireType.Bit64).double(message.heading);
        /* bool dropout_flag = 7; */
        if (message.dropoutFlag !== false)
            writer.tag(7, WireType.Varint).bool(message.dropoutFlag);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message sil.AISMessage
 */
export const AISMessage = new AISMessage$Type();
