// @generated by protobuf-ts 2.11.1 with parameter generate_dependencies
// @generated from protobuf file "sil/environment_state.proto" (package "sil", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Timestamp } from "../google/protobuf/timestamp";
/**
 * @generated from protobuf message sil.EnvironmentState
 */
export interface EnvironmentState {
    /**
     * @generated from protobuf field: google.protobuf.Timestamp stamp = 1
     */
    stamp?: Timestamp;
    /**
     * @generated from protobuf field: sil.EnvironmentState.Wind wind = 2
     */
    wind?: EnvironmentState_Wind;
    /**
     * @generated from protobuf field: sil.EnvironmentState.Current current = 3
     */
    current?: EnvironmentState_Current;
    /**
     * @generated from protobuf field: double visibility_nm = 4
     */
    visibilityNm: number;
    /**
     * @generated from protobuf field: uint32 sea_state_beaufort = 5
     */
    seaStateBeaufort: number;
}
/**
 * @generated from protobuf message sil.EnvironmentState.Wind
 */
export interface EnvironmentState_Wind {
    /**
     * @generated from protobuf field: double direction = 1
     */
    direction: number;
    /**
     * @generated from protobuf field: double speed_mps = 2
     */
    speedMps: number;
}
/**
 * @generated from protobuf message sil.EnvironmentState.Current
 */
export interface EnvironmentState_Current {
    /**
     * @generated from protobuf field: double direction = 1
     */
    direction: number;
    /**
     * @generated from protobuf field: double speed_mps = 2
     */
    speedMps: number;
}
// @generated message type with reflection information, may provide speed optimized methods
class EnvironmentState$Type extends MessageType<EnvironmentState> {
    constructor() {
        super("sil.EnvironmentState", [
            { no: 1, name: "stamp", kind: "message", T: () => Timestamp },
            { no: 2, name: "wind", kind: "message", T: () => EnvironmentState_Wind },
            { no: 3, name: "current", kind: "message", T: () => EnvironmentState_Current },
            { no: 4, name: "visibility_nm", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 5, name: "sea_state_beaufort", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
    create(value?: PartialMessage<EnvironmentState>): EnvironmentState {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.visibilityNm = 0;
        message.seaStateBeaufort = 0;
        if (value !== undefined)
            reflectionMergePartial<EnvironmentState>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: EnvironmentState): EnvironmentState {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* google.protobuf.Timestamp stamp */ 1:
                    message.stamp = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.stamp);
                    break;
                case /* sil.EnvironmentState.Wind wind */ 2:
                    message.wind = EnvironmentState_Wind.internalBinaryRead(reader, reader.uint32(), options, message.wind);
                    break;
                case /* sil.EnvironmentState.Current current */ 3:
                    message.current = EnvironmentState_Current.internalBinaryRead(reader, reader.uint32(), options, message.current);
                    break;
                case /* double visibility_nm */ 4:
                    message.visibilityNm = reader.double();
                    break;
                case /* uint32 sea_state_beaufort */ 5:
                    message.seaStateBeaufort = reader.uint32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: EnvironmentState, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* google.protobuf.Timestamp stamp = 1; */
        if (message.stamp)
            Timestamp.internalBinaryWrite(message.stamp, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* sil.EnvironmentState.Wind wind = 2; */
        if (message.wind)
            EnvironmentState_Wind.internalBinaryWrite(message.wind, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* sil.EnvironmentState.Current current = 3; */
        if (message.current)
            EnvironmentState_Current.internalBinaryWrite(message.current, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* double visibility_nm = 4; */
        if (message.visibilityNm !== 0)
            writer.tag(4, WireType.Bit64).double(message.visibilityNm);
        /* uint32 sea_state_beaufort = 5; */
        if (message.seaStateBeaufort !== 0)
            writer.tag(5, WireType.Varint).uint32(message.seaStateBeaufort);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message sil.EnvironmentState
 */
export const EnvironmentState = new EnvironmentState$Type();
// @generated message type with reflection information, may provide speed optimized methods
class EnvironmentState_Wind$Type extends MessageType<EnvironmentState_Wind> {
    constructor() {
        super("sil.EnvironmentState.Wind", [
            { no: 1, name: "direction", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 2, name: "speed_mps", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ }
        ]);
    }
    create(value?: PartialMessage<EnvironmentState_Wind>): EnvironmentState_Wind {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.direction = 0;
        message.speedMps = 0;
        if (value !== undefined)
            reflectionMergePartial<EnvironmentState_Wind>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: EnvironmentState_Wind): EnvironmentState_Wind {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* double direction */ 1:
                    message.direction = reader.double();
                    break;
                case /* double speed_mps */ 2:
                    message.speedMps = reader.double();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: EnvironmentState_Wind, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* double direction = 1; */
        if (message.direction !== 0)
            writer.tag(1, WireType.Bit64).double(message.direction);
        /* double speed_mps = 2; */
        if (message.speedMps !== 0)
            writer.tag(2, WireType.Bit64).double(message.speedMps);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message sil.EnvironmentState.Wind
 */
export const EnvironmentState_Wind = new EnvironmentState_Wind$Type();
// @generated message type with reflection information, may provide speed optimized methods
class EnvironmentState_Current$Type extends MessageType<EnvironmentState_Current> {
    constructor() {
        super("sil.EnvironmentState.Current", [
            { no: 1, name: "direction", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 2, name: "speed_mps", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ }
        ]);
    }
    create(value?: PartialMessage<EnvironmentState_Current>): EnvironmentState_Current {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.direction = 0;
        message.speedMps = 0;
        if (value !== undefined)
            reflectionMergePartial<EnvironmentState_Current>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: EnvironmentState_Current): EnvironmentState_Current {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* double direction */ 1:
                    message.direction = reader.double();
                    break;
                case /* double speed_mps */ 2:
                    message.speedMps = reader.double();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: EnvironmentState_Current, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* double direction = 1; */
        if (message.direction !== 0)
            writer.tag(1, WireType.Bit64).double(message.direction);
        /* double speed_mps = 2; */
        if (message.speedMps !== 0)
            writer.tag(2, WireType.Bit64).double(message.speedMps);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message sil.EnvironmentState.Current
 */
export const EnvironmentState_Current = new EnvironmentState_Current$Type();
