// @generated by protobuf-ts 2.11.1 with parameter generate_dependencies
// @generated from protobuf file "sil/fault_trigger.proto" (package "sil", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message sil.TriggerRequest
 */
export interface TriggerRequest {
    /**
     * @generated from protobuf field: string fault_type = 1
     */
    faultType: string;
    /**
     * @generated from protobuf field: string payload_json = 2
     */
    payloadJson: string;
}
/**
 * @generated from protobuf message sil.TriggerResponse
 */
export interface TriggerResponse {
    /**
     * @generated from protobuf field: string fault_id = 1
     */
    faultId: string;
}
/**
 * @generated from protobuf message sil.ListFaultsRequest
 */
export interface ListFaultsRequest {
}
/**
 * @generated from protobuf message sil.ListFaultsResponse
 */
export interface ListFaultsResponse {
    /**
     * @generated from protobuf field: repeated sil.ActiveFault active = 1
     */
    active: ActiveFault[];
}
/**
 * @generated from protobuf message sil.ActiveFault
 */
export interface ActiveFault {
    /**
     * @generated from protobuf field: string fault_id = 1
     */
    faultId: string;
    /**
     * @generated from protobuf field: string fault_type = 2
     */
    faultType: string;
    /**
     * @generated from protobuf field: string stamp = 3
     */
    stamp: string;
}
/**
 * @generated from protobuf message sil.CancelRequest
 */
export interface CancelRequest {
    /**
     * @generated from protobuf field: string fault_id = 1
     */
    faultId: string;
}
/**
 * @generated from protobuf message sil.CancelResponse
 */
export interface CancelResponse {
    /**
     * @generated from protobuf field: bool success = 1
     */
    success: boolean;
}
// @generated message type with reflection information, may provide speed optimized methods
class TriggerRequest$Type extends MessageType<TriggerRequest> {
    constructor() {
        super("sil.TriggerRequest", [
            { no: 1, name: "fault_type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "payload_json", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<TriggerRequest>): TriggerRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.faultType = "";
        message.payloadJson = "";
        if (value !== undefined)
            reflectionMergePartial<TriggerRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TriggerRequest): TriggerRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string fault_type */ 1:
                    message.faultType = reader.string();
                    break;
                case /* string payload_json */ 2:
                    message.payloadJson = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TriggerRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string fault_type = 1; */
        if (message.faultType !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.faultType);
        /* string payload_json = 2; */
        if (message.payloadJson !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.payloadJson);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message sil.TriggerRequest
 */
export const TriggerRequest = new TriggerRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TriggerResponse$Type extends MessageType<TriggerResponse> {
    constructor() {
        super("sil.TriggerResponse", [
            { no: 1, name: "fault_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<TriggerResponse>): TriggerResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.faultId = "";
        if (value !== undefined)
            reflectionMergePartial<TriggerResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TriggerResponse): TriggerResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string fault_id */ 1:
                    message.faultId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TriggerResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string fault_id = 1; */
        if (message.faultId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.faultId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message sil.TriggerResponse
 */
export const TriggerResponse = new TriggerResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListFaultsRequest$Type extends MessageType<ListFaultsRequest> {
    constructor() {
        super("sil.ListFaultsRequest", []);
    }
    create(value?: PartialMessage<ListFaultsRequest>): ListFaultsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<ListFaultsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListFaultsRequest): ListFaultsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListFaultsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message sil.ListFaultsRequest
 */
export const ListFaultsRequest = new ListFaultsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListFaultsResponse$Type extends MessageType<ListFaultsResponse> {
    constructor() {
        super("sil.ListFaultsResponse", [
            { no: 1, name: "active", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => ActiveFault }
        ]);
    }
    create(value?: PartialMessage<ListFaultsResponse>): ListFaultsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.active = [];
        if (value !== undefined)
            reflectionMergePartial<ListFaultsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListFaultsResponse): ListFaultsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated sil.ActiveFault active */ 1:
                    message.active.push(ActiveFault.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListFaultsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated sil.ActiveFault active = 1; */
        for (let i = 0; i < message.active.length; i++)
            ActiveFault.internalBinaryWrite(message.active[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message sil.ListFaultsResponse
 */
export const ListFaultsResponse = new ListFaultsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ActiveFault$Type extends MessageType<ActiveFault> {
    constructor() {
        super("sil.ActiveFault", [
            { no: 1, name: "fault_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "fault_type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "stamp", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ActiveFault>): ActiveFault {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.faultId = "";
        message.faultType = "";
        message.stamp = "";
        if (value !== undefined)
            reflectionMergePartial<ActiveFault>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ActiveFault): ActiveFault {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string fault_id */ 1:
                    message.faultId = reader.string();
                    break;
                case /* string fault_type */ 2:
                    message.faultType = reader.string();
                    break;
                case /* string stamp */ 3:
                    message.stamp = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ActiveFault, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string fault_id = 1; */
        if (message.faultId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.faultId);
        /* string fault_type = 2; */
        if (message.faultType !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.faultType);
        /* string stamp = 3; */
        if (message.stamp !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.stamp);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message sil.ActiveFault
 */
export const ActiveFault = new ActiveFault$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CancelRequest$Type extends MessageType<CancelRequest> {
    constructor() {
        super("sil.CancelRequest", [
            { no: 1, name: "fault_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<CancelRequest>): CancelRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.faultId = "";
        if (value !== undefined)
            reflectionMergePartial<CancelRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CancelRequest): CancelRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string fault_id */ 1:
                    message.faultId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CancelRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string fault_id = 1; */
        if (message.faultId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.faultId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message sil.CancelRequest
 */
export const CancelRequest = new CancelRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CancelResponse$Type extends MessageType<CancelResponse> {
    constructor() {
        super("sil.CancelResponse", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<CancelResponse>): CancelResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.success = false;
        if (value !== undefined)
            reflectionMergePartial<CancelResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CancelResponse): CancelResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool success */ 1:
                    message.success = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CancelResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool success = 1; */
        if (message.success !== false)
            writer.tag(1, WireType.Varint).bool(message.success);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message sil.CancelResponse
 */
export const CancelResponse = new CancelResponse$Type();
/**
 * @generated ServiceType for protobuf service sil.FaultTriggerService
 */
export const FaultTriggerService = new ServiceType("sil.FaultTriggerService", [
    { name: "Trigger", options: {}, I: TriggerRequest, O: TriggerResponse },
    { name: "ListFaults", options: {}, I: ListFaultsRequest, O: ListFaultsResponse },
    { name: "Cancel", options: {}, I: CancelRequest, O: CancelResponse }
]);
