// @generated by protobuf-ts 2.11.1 with parameter generate_dependencies
// @generated from protobuf file "sil/fault_trigger.proto" (package "sil", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { FaultTriggerService } from "./fault_trigger";
import type { CancelResponse } from "./fault_trigger";
import type { CancelRequest } from "./fault_trigger";
import type { ListFaultsResponse } from "./fault_trigger";
import type { ListFaultsRequest } from "./fault_trigger";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { TriggerResponse } from "./fault_trigger";
import type { TriggerRequest } from "./fault_trigger";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service sil.FaultTriggerService
 */
export interface IFaultTriggerServiceClient {
    /**
     * @generated from protobuf rpc: Trigger
     */
    trigger(input: TriggerRequest, options?: RpcOptions): UnaryCall<TriggerRequest, TriggerResponse>;
    /**
     * @generated from protobuf rpc: ListFaults
     */
    listFaults(input: ListFaultsRequest, options?: RpcOptions): UnaryCall<ListFaultsRequest, ListFaultsResponse>;
    /**
     * @generated from protobuf rpc: Cancel
     */
    cancel(input: CancelRequest, options?: RpcOptions): UnaryCall<CancelRequest, CancelResponse>;
}
/**
 * @generated from protobuf service sil.FaultTriggerService
 */
export class FaultTriggerServiceClient implements IFaultTriggerServiceClient, ServiceInfo {
    typeName = FaultTriggerService.typeName;
    methods = FaultTriggerService.methods;
    options = FaultTriggerService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: Trigger
     */
    trigger(input: TriggerRequest, options?: RpcOptions): UnaryCall<TriggerRequest, TriggerResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<TriggerRequest, TriggerResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListFaults
     */
    listFaults(input: ListFaultsRequest, options?: RpcOptions): UnaryCall<ListFaultsRequest, ListFaultsResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListFaultsRequest, ListFaultsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Cancel
     */
    cancel(input: CancelRequest, options?: RpcOptions): UnaryCall<CancelRequest, CancelResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<CancelRequest, CancelResponse>("unary", this._transport, method, opt, input);
    }
}
