// @generated by protobuf-ts 2.11.1 with parameter generate_dependencies
// @generated from protobuf file "sil/fault_event.proto" (package "sil", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Timestamp } from "../google/protobuf/timestamp";
/**
 * @generated from protobuf message sil.FaultEvent
 */
export interface FaultEvent {
    /**
     * @generated from protobuf field: google.protobuf.Timestamp stamp = 1
     */
    stamp?: Timestamp;
    /**
     * @generated from protobuf field: string fault_type = 2
     */
    faultType: string;
    /**
     * @generated from protobuf field: string payload_json = 3
     */
    payloadJson: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class FaultEvent$Type extends MessageType<FaultEvent> {
    constructor() {
        super("sil.FaultEvent", [
            { no: 1, name: "stamp", kind: "message", T: () => Timestamp },
            { no: 2, name: "fault_type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "payload_json", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<FaultEvent>): FaultEvent {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.faultType = "";
        message.payloadJson = "";
        if (value !== undefined)
            reflectionMergePartial<FaultEvent>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: FaultEvent): FaultEvent {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* google.protobuf.Timestamp stamp */ 1:
                    message.stamp = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.stamp);
                    break;
                case /* string fault_type */ 2:
                    message.faultType = reader.string();
                    break;
                case /* string payload_json */ 3:
                    message.payloadJson = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: FaultEvent, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* google.protobuf.Timestamp stamp = 1; */
        if (message.stamp)
            Timestamp.internalBinaryWrite(message.stamp, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* string fault_type = 2; */
        if (message.faultType !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.faultType);
        /* string payload_json = 3; */
        if (message.payloadJson !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.payloadJson);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message sil.FaultEvent
 */
export const FaultEvent = new FaultEvent$Type();
