// @generated by protobuf-ts 2.11.1 with parameter generate_dependencies
// @generated from protobuf file "sil/lifecycle_status.proto" (package "sil", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Timestamp } from "../google/protobuf/timestamp";
/**
 * @generated from protobuf message sil.LifecycleStatus
 */
export interface LifecycleStatus {
    /**
     * @generated from protobuf field: google.protobuf.Timestamp stamp = 1
     */
    stamp?: Timestamp;
    /**
     * @generated from protobuf field: sil.LifecycleStatus.LifecycleState current_state = 2
     */
    currentState: LifecycleStatus_LifecycleState;
    /**
     * @generated from protobuf field: string scenario_id = 3
     */
    scenarioId: string;
    /**
     * @generated from protobuf field: string scenario_hash = 4
     */
    scenarioHash: string;
    /**
     * @generated from protobuf field: double sim_time = 5
     */
    simTime: number;
    /**
     * @generated from protobuf field: double wall_time = 6
     */
    wallTime: number;
    /**
     * @generated from protobuf field: double sim_rate = 7
     */
    simRate: number;
}
/**
 * @generated from protobuf enum sil.LifecycleStatus.LifecycleState
 */
export enum LifecycleStatus_LifecycleState {
    /**
     * @generated from protobuf enum value: LIFECYCLE_STATE_UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: LIFECYCLE_STATE_UNCONFIGURED = 1;
     */
    UNCONFIGURED = 1,
    /**
     * @generated from protobuf enum value: LIFECYCLE_STATE_INACTIVE = 2;
     */
    INACTIVE = 2,
    /**
     * @generated from protobuf enum value: LIFECYCLE_STATE_ACTIVE = 3;
     */
    ACTIVE = 3,
    /**
     * @generated from protobuf enum value: LIFECYCLE_STATE_DEACTIVATING = 4;
     */
    DEACTIVATING = 4,
    /**
     * @generated from protobuf enum value: LIFECYCLE_STATE_FINALIZED = 5;
     */
    FINALIZED = 5
}
// @generated message type with reflection information, may provide speed optimized methods
class LifecycleStatus$Type extends MessageType<LifecycleStatus> {
    constructor() {
        super("sil.LifecycleStatus", [
            { no: 1, name: "stamp", kind: "message", T: () => Timestamp },
            { no: 2, name: "current_state", kind: "enum", T: () => ["sil.LifecycleStatus.LifecycleState", LifecycleStatus_LifecycleState, "LIFECYCLE_STATE_"] },
            { no: 3, name: "scenario_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "scenario_hash", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "sim_time", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 6, name: "wall_time", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 7, name: "sim_rate", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ }
        ]);
    }
    create(value?: PartialMessage<LifecycleStatus>): LifecycleStatus {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.currentState = 0;
        message.scenarioId = "";
        message.scenarioHash = "";
        message.simTime = 0;
        message.wallTime = 0;
        message.simRate = 0;
        if (value !== undefined)
            reflectionMergePartial<LifecycleStatus>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: LifecycleStatus): LifecycleStatus {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* google.protobuf.Timestamp stamp */ 1:
                    message.stamp = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.stamp);
                    break;
                case /* sil.LifecycleStatus.LifecycleState current_state */ 2:
                    message.currentState = reader.int32();
                    break;
                case /* string scenario_id */ 3:
                    message.scenarioId = reader.string();
                    break;
                case /* string scenario_hash */ 4:
                    message.scenarioHash = reader.string();
                    break;
                case /* double sim_time */ 5:
                    message.simTime = reader.double();
                    break;
                case /* double wall_time */ 6:
                    message.wallTime = reader.double();
                    break;
                case /* double sim_rate */ 7:
                    message.simRate = reader.double();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: LifecycleStatus, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* google.protobuf.Timestamp stamp = 1; */
        if (message.stamp)
            Timestamp.internalBinaryWrite(message.stamp, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* sil.LifecycleStatus.LifecycleState current_state = 2; */
        if (message.currentState !== 0)
            writer.tag(2, WireType.Varint).int32(message.currentState);
        /* string scenario_id = 3; */
        if (message.scenarioId !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.scenarioId);
        /* string scenario_hash = 4; */
        if (message.scenarioHash !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.scenarioHash);
        /* double sim_time = 5; */
        if (message.simTime !== 0)
            writer.tag(5, WireType.Bit64).double(message.simTime);
        /* double wall_time = 6; */
        if (message.wallTime !== 0)
            writer.tag(6, WireType.Bit64).double(message.wallTime);
        /* double sim_rate = 7; */
        if (message.simRate !== 0)
            writer.tag(7, WireType.Bit64).double(message.simRate);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message sil.LifecycleStatus
 */
export const LifecycleStatus = new LifecycleStatus$Type();
