// @generated by protobuf-ts 2.11.1 with parameter generate_dependencies
// @generated from protobuf file "sil/own_ship_state.proto" (package "sil", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Timestamp } from "../google/protobuf/timestamp";
/**
 * @generated from protobuf message sil.OwnShipState
 */
export interface OwnShipState {
    /**
     * @generated from protobuf field: google.protobuf.Timestamp stamp = 1
     */
    stamp?: Timestamp;
    /**
     * @generated from protobuf field: sil.OwnShipState.Pose pose = 2
     */
    pose?: OwnShipState_Pose;
    /**
     * @generated from protobuf field: sil.OwnShipState.Kinematics kinematics = 3
     */
    kinematics?: OwnShipState_Kinematics;
    /**
     * @generated from protobuf field: sil.OwnShipState.ControlState control_state = 4
     */
    controlState?: OwnShipState_ControlState;
}
/**
 * @generated from protobuf message sil.OwnShipState.Pose
 */
export interface OwnShipState_Pose {
    /**
     * @generated from protobuf field: double lat = 1
     */
    lat: number;
    /**
     * @generated from protobuf field: double lon = 2
     */
    lon: number;
    /**
     * @generated from protobuf field: double heading = 3
     */
    heading: number;
}
/**
 * @generated from protobuf message sil.OwnShipState.Kinematics
 */
export interface OwnShipState_Kinematics {
    /**
     * @generated from protobuf field: double sog = 1
     */
    sog: number;
    /**
     * @generated from protobuf field: double cog = 2
     */
    cog: number;
    /**
     * @generated from protobuf field: double rot = 3
     */
    rot: number;
    /**
     * @generated from protobuf field: double u = 4
     */
    u: number;
    /**
     * @generated from protobuf field: double v = 5
     */
    v: number;
    /**
     * @generated from protobuf field: double r = 6
     */
    r: number;
}
/**
 * @generated from protobuf message sil.OwnShipState.ControlState
 */
export interface OwnShipState_ControlState {
    /**
     * @generated from protobuf field: double rudder_angle = 1
     */
    rudderAngle: number;
    /**
     * @generated from protobuf field: double throttle = 2
     */
    throttle: number;
}
// @generated message type with reflection information, may provide speed optimized methods
class OwnShipState$Type extends MessageType<OwnShipState> {
    constructor() {
        super("sil.OwnShipState", [
            { no: 1, name: "stamp", kind: "message", T: () => Timestamp },
            { no: 2, name: "pose", kind: "message", T: () => OwnShipState_Pose },
            { no: 3, name: "kinematics", kind: "message", T: () => OwnShipState_Kinematics },
            { no: 4, name: "control_state", kind: "message", T: () => OwnShipState_ControlState }
        ]);
    }
    create(value?: PartialMessage<OwnShipState>): OwnShipState {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<OwnShipState>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: OwnShipState): OwnShipState {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* google.protobuf.Timestamp stamp */ 1:
                    message.stamp = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.stamp);
                    break;
                case /* sil.OwnShipState.Pose pose */ 2:
                    message.pose = OwnShipState_Pose.internalBinaryRead(reader, reader.uint32(), options, message.pose);
                    break;
                case /* sil.OwnShipState.Kinematics kinematics */ 3:
                    message.kinematics = OwnShipState_Kinematics.internalBinaryRead(reader, reader.uint32(), options, message.kinematics);
                    break;
                case /* sil.OwnShipState.ControlState control_state */ 4:
                    message.controlState = OwnShipState_ControlState.internalBinaryRead(reader, reader.uint32(), options, message.controlState);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: OwnShipState, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* google.protobuf.Timestamp stamp = 1; */
        if (message.stamp)
            Timestamp.internalBinaryWrite(message.stamp, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* sil.OwnShipState.Pose pose = 2; */
        if (message.pose)
            OwnShipState_Pose.internalBinaryWrite(message.pose, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* sil.OwnShipState.Kinematics kinematics = 3; */
        if (message.kinematics)
            OwnShipState_Kinematics.internalBinaryWrite(message.kinematics, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* sil.OwnShipState.ControlState control_state = 4; */
        if (message.controlState)
            OwnShipState_ControlState.internalBinaryWrite(message.controlState, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message sil.OwnShipState
 */
export const OwnShipState = new OwnShipState$Type();
// @generated message type with reflection information, may provide speed optimized methods
class OwnShipState_Pose$Type extends MessageType<OwnShipState_Pose> {
    constructor() {
        super("sil.OwnShipState.Pose", [
            { no: 1, name: "lat", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 2, name: "lon", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 3, name: "heading", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ }
        ]);
    }
    create(value?: PartialMessage<OwnShipState_Pose>): OwnShipState_Pose {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.lat = 0;
        message.lon = 0;
        message.heading = 0;
        if (value !== undefined)
            reflectionMergePartial<OwnShipState_Pose>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: OwnShipState_Pose): OwnShipState_Pose {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* double lat */ 1:
                    message.lat = reader.double();
                    break;
                case /* double lon */ 2:
                    message.lon = reader.double();
                    break;
                case /* double heading */ 3:
                    message.heading = reader.double();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: OwnShipState_Pose, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* double lat = 1; */
        if (message.lat !== 0)
            writer.tag(1, WireType.Bit64).double(message.lat);
        /* double lon = 2; */
        if (message.lon !== 0)
            writer.tag(2, WireType.Bit64).double(message.lon);
        /* double heading = 3; */
        if (message.heading !== 0)
            writer.tag(3, WireType.Bit64).double(message.heading);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message sil.OwnShipState.Pose
 */
export const OwnShipState_Pose = new OwnShipState_Pose$Type();
// @generated message type with reflection information, may provide speed optimized methods
class OwnShipState_Kinematics$Type extends MessageType<OwnShipState_Kinematics> {
    constructor() {
        super("sil.OwnShipState.Kinematics", [
            { no: 1, name: "sog", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 2, name: "cog", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 3, name: "rot", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 4, name: "u", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 5, name: "v", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 6, name: "r", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ }
        ]);
    }
    create(value?: PartialMessage<OwnShipState_Kinematics>): OwnShipState_Kinematics {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.sog = 0;
        message.cog = 0;
        message.rot = 0;
        message.u = 0;
        message.v = 0;
        message.r = 0;
        if (value !== undefined)
            reflectionMergePartial<OwnShipState_Kinematics>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: OwnShipState_Kinematics): OwnShipState_Kinematics {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* double sog */ 1:
                    message.sog = reader.double();
                    break;
                case /* double cog */ 2:
                    message.cog = reader.double();
                    break;
                case /* double rot */ 3:
                    message.rot = reader.double();
                    break;
                case /* double u */ 4:
                    message.u = reader.double();
                    break;
                case /* double v */ 5:
                    message.v = reader.double();
                    break;
                case /* double r */ 6:
                    message.r = reader.double();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: OwnShipState_Kinematics, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* double sog = 1; */
        if (message.sog !== 0)
            writer.tag(1, WireType.Bit64).double(message.sog);
        /* double cog = 2; */
        if (message.cog !== 0)
            writer.tag(2, WireType.Bit64).double(message.cog);
        /* double rot = 3; */
        if (message.rot !== 0)
            writer.tag(3, WireType.Bit64).double(message.rot);
        /* double u = 4; */
        if (message.u !== 0)
            writer.tag(4, WireType.Bit64).double(message.u);
        /* double v = 5; */
        if (message.v !== 0)
            writer.tag(5, WireType.Bit64).double(message.v);
        /* double r = 6; */
        if (message.r !== 0)
            writer.tag(6, WireType.Bit64).double(message.r);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message sil.OwnShipState.Kinematics
 */
export const OwnShipState_Kinematics = new OwnShipState_Kinematics$Type();
// @generated message type with reflection information, may provide speed optimized methods
class OwnShipState_ControlState$Type extends MessageType<OwnShipState_ControlState> {
    constructor() {
        super("sil.OwnShipState.ControlState", [
            { no: 1, name: "rudder_angle", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 2, name: "throttle", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ }
        ]);
    }
    create(value?: PartialMessage<OwnShipState_ControlState>): OwnShipState_ControlState {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.rudderAngle = 0;
        message.throttle = 0;
        if (value !== undefined)
            reflectionMergePartial<OwnShipState_ControlState>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: OwnShipState_ControlState): OwnShipState_ControlState {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* double rudder_angle */ 1:
                    message.rudderAngle = reader.double();
                    break;
                case /* double throttle */ 2:
                    message.throttle = reader.double();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: OwnShipState_ControlState, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* double rudder_angle = 1; */
        if (message.rudderAngle !== 0)
            writer.tag(1, WireType.Bit64).double(message.rudderAngle);
        /* double throttle = 2; */
        if (message.throttle !== 0)
            writer.tag(2, WireType.Bit64).double(message.throttle);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message sil.OwnShipState.ControlState
 */
export const OwnShipState_ControlState = new OwnShipState_ControlState$Type();
