// @generated by protobuf-ts 2.11.1 with parameter generate_dependencies
// @generated from protobuf file "sil/scoring_row.proto" (package "sil", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Timestamp } from "../google/protobuf/timestamp";
/**
 * @generated from protobuf message sil.ScoringRow
 */
export interface ScoringRow {
    /**
     * @generated from protobuf field: google.protobuf.Timestamp stamp = 1
     */
    stamp?: Timestamp;
    /**
     * @generated from protobuf field: double safety = 2
     */
    safety: number;
    /**
     * @generated from protobuf field: double rule_compliance = 3
     */
    ruleCompliance: number;
    /**
     * @generated from protobuf field: double delay = 4
     */
    delay: number;
    /**
     * @generated from protobuf field: double magnitude = 5
     */
    magnitude: number;
    /**
     * @generated from protobuf field: double phase = 6
     */
    phase: number;
    /**
     * @generated from protobuf field: double plausibility = 7
     */
    plausibility: number;
    /**
     * @generated from protobuf field: double total = 8
     */
    total: number;
}
// @generated message type with reflection information, may provide speed optimized methods
class ScoringRow$Type extends MessageType<ScoringRow> {
    constructor() {
        super("sil.ScoringRow", [
            { no: 1, name: "stamp", kind: "message", T: () => Timestamp },
            { no: 2, name: "safety", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 3, name: "rule_compliance", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 4, name: "delay", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 5, name: "magnitude", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 6, name: "phase", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 7, name: "plausibility", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 8, name: "total", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ }
        ]);
    }
    create(value?: PartialMessage<ScoringRow>): ScoringRow {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.safety = 0;
        message.ruleCompliance = 0;
        message.delay = 0;
        message.magnitude = 0;
        message.phase = 0;
        message.plausibility = 0;
        message.total = 0;
        if (value !== undefined)
            reflectionMergePartial<ScoringRow>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ScoringRow): ScoringRow {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* google.protobuf.Timestamp stamp */ 1:
                    message.stamp = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.stamp);
                    break;
                case /* double safety */ 2:
                    message.safety = reader.double();
                    break;
                case /* double rule_compliance */ 3:
                    message.ruleCompliance = reader.double();
                    break;
                case /* double delay */ 4:
                    message.delay = reader.double();
                    break;
                case /* double magnitude */ 5:
                    message.magnitude = reader.double();
                    break;
                case /* double phase */ 6:
                    message.phase = reader.double();
                    break;
                case /* double plausibility */ 7:
                    message.plausibility = reader.double();
                    break;
                case /* double total */ 8:
                    message.total = reader.double();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ScoringRow, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* google.protobuf.Timestamp stamp = 1; */
        if (message.stamp)
            Timestamp.internalBinaryWrite(message.stamp, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* double safety = 2; */
        if (message.safety !== 0)
            writer.tag(2, WireType.Bit64).double(message.safety);
        /* double rule_compliance = 3; */
        if (message.ruleCompliance !== 0)
            writer.tag(3, WireType.Bit64).double(message.ruleCompliance);
        /* double delay = 4; */
        if (message.delay !== 0)
            writer.tag(4, WireType.Bit64).double(message.delay);
        /* double magnitude = 5; */
        if (message.magnitude !== 0)
            writer.tag(5, WireType.Bit64).double(message.magnitude);
        /* double phase = 6; */
        if (message.phase !== 0)
            writer.tag(6, WireType.Bit64).double(message.phase);
        /* double plausibility = 7; */
        if (message.plausibility !== 0)
            writer.tag(7, WireType.Bit64).double(message.plausibility);
        /* double total = 8; */
        if (message.total !== 0)
            writer.tag(8, WireType.Bit64).double(message.total);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message sil.ScoringRow
 */
export const ScoringRow = new ScoringRow$Type();
