// @generated by protobuf-ts 2.11.1 with parameter generate_dependencies
// @generated from protobuf file "sil/sim_clock.proto" (package "sil", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message sil.SetRateRequest
 */
export interface SetRateRequest {
    /**
     * @generated from protobuf field: double rate = 1
     */
    rate: number;
}
/**
 * @generated from protobuf message sil.SetRateResponse
 */
export interface SetRateResponse {
    /**
     * @generated from protobuf field: bool success = 1
     */
    success: boolean;
}
/**
 * @generated from protobuf message sil.GetTimeRequest
 */
export interface GetTimeRequest {
}
/**
 * @generated from protobuf message sil.GetTimeResponse
 */
export interface GetTimeResponse {
    /**
     * @generated from protobuf field: double sim_time = 1
     */
    simTime: number;
    /**
     * @generated from protobuf field: double wall_time = 2
     */
    wallTime: number;
}
// @generated message type with reflection information, may provide speed optimized methods
class SetRateRequest$Type extends MessageType<SetRateRequest> {
    constructor() {
        super("sil.SetRateRequest", [
            { no: 1, name: "rate", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ }
        ]);
    }
    create(value?: PartialMessage<SetRateRequest>): SetRateRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.rate = 0;
        if (value !== undefined)
            reflectionMergePartial<SetRateRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SetRateRequest): SetRateRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* double rate */ 1:
                    message.rate = reader.double();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SetRateRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* double rate = 1; */
        if (message.rate !== 0)
            writer.tag(1, WireType.Bit64).double(message.rate);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message sil.SetRateRequest
 */
export const SetRateRequest = new SetRateRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SetRateResponse$Type extends MessageType<SetRateResponse> {
    constructor() {
        super("sil.SetRateResponse", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<SetRateResponse>): SetRateResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.success = false;
        if (value !== undefined)
            reflectionMergePartial<SetRateResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SetRateResponse): SetRateResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool success */ 1:
                    message.success = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SetRateResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool success = 1; */
        if (message.success !== false)
            writer.tag(1, WireType.Varint).bool(message.success);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message sil.SetRateResponse
 */
export const SetRateResponse = new SetRateResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetTimeRequest$Type extends MessageType<GetTimeRequest> {
    constructor() {
        super("sil.GetTimeRequest", []);
    }
    create(value?: PartialMessage<GetTimeRequest>): GetTimeRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetTimeRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetTimeRequest): GetTimeRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetTimeRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message sil.GetTimeRequest
 */
export const GetTimeRequest = new GetTimeRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetTimeResponse$Type extends MessageType<GetTimeResponse> {
    constructor() {
        super("sil.GetTimeResponse", [
            { no: 1, name: "sim_time", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 2, name: "wall_time", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ }
        ]);
    }
    create(value?: PartialMessage<GetTimeResponse>): GetTimeResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.simTime = 0;
        message.wallTime = 0;
        if (value !== undefined)
            reflectionMergePartial<GetTimeResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetTimeResponse): GetTimeResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* double sim_time */ 1:
                    message.simTime = reader.double();
                    break;
                case /* double wall_time */ 2:
                    message.wallTime = reader.double();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetTimeResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* double sim_time = 1; */
        if (message.simTime !== 0)
            writer.tag(1, WireType.Bit64).double(message.simTime);
        /* double wall_time = 2; */
        if (message.wallTime !== 0)
            writer.tag(2, WireType.Bit64).double(message.wallTime);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message sil.GetTimeResponse
 */
export const GetTimeResponse = new GetTimeResponse$Type();
/**
 * @generated ServiceType for protobuf service sil.SimClockService
 */
export const SimClockService = new ServiceType("sil.SimClockService", [
    { name: "SetRate", options: {}, I: SetRateRequest, O: SetRateResponse },
    { name: "GetTime", options: {}, I: GetTimeRequest, O: GetTimeResponse }
]);
