// @generated by protobuf-ts 2.11.1 with parameter generate_dependencies
// @generated from protobuf file "sil/asdr_event.proto" (package "sil", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Timestamp } from "../google/protobuf/timestamp";
/**
 * @generated from protobuf message sil.ASDREvent
 */
export interface ASDREvent {
    /**
     * @generated from protobuf field: google.protobuf.Timestamp stamp = 1
     */
    stamp?: Timestamp;
    /**
     * @generated from protobuf field: string event_type = 2
     */
    eventType: string;
    /**
     * @generated from protobuf field: string rule_ref = 3
     */
    ruleRef: string;
    /**
     * @generated from protobuf field: string decision_id = 4
     */
    decisionId: string;
    /**
     * @generated from protobuf field: sil.ASDREvent.Verdict verdict = 5
     */
    verdict: ASDREvent_Verdict;
    /**
     * @generated from protobuf field: string payload_json = 6
     */
    payloadJson: string;
}
/**
 * @generated from protobuf enum sil.ASDREvent.Verdict
 */
export enum ASDREvent_Verdict {
    /**
     * @generated from protobuf enum value: VERDICT_UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: VERDICT_PASS = 1;
     */
    PASS = 1,
    /**
     * @generated from protobuf enum value: VERDICT_RISK = 2;
     */
    RISK = 2,
    /**
     * @generated from protobuf enum value: VERDICT_FAIL = 3;
     */
    FAIL = 3
}
// @generated message type with reflection information, may provide speed optimized methods
class ASDREvent$Type extends MessageType<ASDREvent> {
    constructor() {
        super("sil.ASDREvent", [
            { no: 1, name: "stamp", kind: "message", T: () => Timestamp },
            { no: 2, name: "event_type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "rule_ref", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "decision_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "verdict", kind: "enum", T: () => ["sil.ASDREvent.Verdict", ASDREvent_Verdict, "VERDICT_"] },
            { no: 6, name: "payload_json", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ASDREvent>): ASDREvent {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.eventType = "";
        message.ruleRef = "";
        message.decisionId = "";
        message.verdict = 0;
        message.payloadJson = "";
        if (value !== undefined)
            reflectionMergePartial<ASDREvent>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ASDREvent): ASDREvent {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* google.protobuf.Timestamp stamp */ 1:
                    message.stamp = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.stamp);
                    break;
                case /* string event_type */ 2:
                    message.eventType = reader.string();
                    break;
                case /* string rule_ref */ 3:
                    message.ruleRef = reader.string();
                    break;
                case /* string decision_id */ 4:
                    message.decisionId = reader.string();
                    break;
                case /* sil.ASDREvent.Verdict verdict */ 5:
                    message.verdict = reader.int32();
                    break;
                case /* string payload_json */ 6:
                    message.payloadJson = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ASDREvent, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* google.protobuf.Timestamp stamp = 1; */
        if (message.stamp)
            Timestamp.internalBinaryWrite(message.stamp, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* string event_type = 2; */
        if (message.eventType !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.eventType);
        /* string rule_ref = 3; */
        if (message.ruleRef !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.ruleRef);
        /* string decision_id = 4; */
        if (message.decisionId !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.decisionId);
        /* sil.ASDREvent.Verdict verdict = 5; */
        if (message.verdict !== 0)
            writer.tag(5, WireType.Varint).int32(message.verdict);
        /* string payload_json = 6; */
        if (message.payloadJson !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.payloadJson);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message sil.ASDREvent
 */
export const ASDREvent = new ASDREvent$Type();
