// @generated by protobuf-ts 2.11.1 with parameter generate_dependencies
// @generated from protobuf file "sil/export_evidence.proto" (package "sil", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { ExportEvidenceService } from "./export_evidence";
import type { PostProcessArrowResponse } from "./export_evidence";
import type { PostProcessArrowRequest } from "./export_evidence";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { PackMarzipResponse } from "./export_evidence";
import type { PackMarzipRequest } from "./export_evidence";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service sil.ExportEvidenceService
 */
export interface IExportEvidenceServiceClient {
    /**
     * @generated from protobuf rpc: PackMarzip
     */
    packMarzip(input: PackMarzipRequest, options?: RpcOptions): UnaryCall<PackMarzipRequest, PackMarzipResponse>;
    /**
     * @generated from protobuf rpc: PostProcessArrow
     */
    postProcessArrow(input: PostProcessArrowRequest, options?: RpcOptions): UnaryCall<PostProcessArrowRequest, PostProcessArrowResponse>;
}
/**
 * @generated from protobuf service sil.ExportEvidenceService
 */
export class ExportEvidenceServiceClient implements IExportEvidenceServiceClient, ServiceInfo {
    typeName = ExportEvidenceService.typeName;
    methods = ExportEvidenceService.methods;
    options = ExportEvidenceService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: PackMarzip
     */
    packMarzip(input: PackMarzipRequest, options?: RpcOptions): UnaryCall<PackMarzipRequest, PackMarzipResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<PackMarzipRequest, PackMarzipResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: PostProcessArrow
     */
    postProcessArrow(input: PostProcessArrowRequest, options?: RpcOptions): UnaryCall<PostProcessArrowRequest, PostProcessArrowResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<PostProcessArrowRequest, PostProcessArrowResponse>("unary", this._transport, method, opt, input);
    }
}
