// @generated by protobuf-ts 2.11.1 with parameter generate_dependencies
// @generated from protobuf file "sil/export_evidence.proto" (package "sil", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message sil.PackMarzipRequest
 */
export interface PackMarzipRequest {
    /**
     * @generated from protobuf field: string run_id = 1
     */
    runId: string;
}
/**
 * @generated from protobuf message sil.PackMarzipResponse
 */
export interface PackMarzipResponse {
    /**
     * @generated from protobuf field: string download_url = 1
     */
    downloadUrl: string;
    /**
     * @generated from protobuf field: string status = 2
     */
    status: string;
}
/**
 * @generated from protobuf message sil.PostProcessArrowRequest
 */
export interface PostProcessArrowRequest {
    /**
     * @generated from protobuf field: string run_id = 1
     */
    runId: string;
}
/**
 * @generated from protobuf message sil.PostProcessArrowResponse
 */
export interface PostProcessArrowResponse {
    /**
     * @generated from protobuf field: string arrow_path = 1
     */
    arrowPath: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class PackMarzipRequest$Type extends MessageType<PackMarzipRequest> {
    constructor() {
        super("sil.PackMarzipRequest", [
            { no: 1, name: "run_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<PackMarzipRequest>): PackMarzipRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.runId = "";
        if (value !== undefined)
            reflectionMergePartial<PackMarzipRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PackMarzipRequest): PackMarzipRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string run_id */ 1:
                    message.runId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PackMarzipRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string run_id = 1; */
        if (message.runId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.runId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message sil.PackMarzipRequest
 */
export const PackMarzipRequest = new PackMarzipRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PackMarzipResponse$Type extends MessageType<PackMarzipResponse> {
    constructor() {
        super("sil.PackMarzipResponse", [
            { no: 1, name: "download_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "status", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<PackMarzipResponse>): PackMarzipResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.downloadUrl = "";
        message.status = "";
        if (value !== undefined)
            reflectionMergePartial<PackMarzipResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PackMarzipResponse): PackMarzipResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string download_url */ 1:
                    message.downloadUrl = reader.string();
                    break;
                case /* string status */ 2:
                    message.status = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PackMarzipResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string download_url = 1; */
        if (message.downloadUrl !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.downloadUrl);
        /* string status = 2; */
        if (message.status !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.status);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message sil.PackMarzipResponse
 */
export const PackMarzipResponse = new PackMarzipResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PostProcessArrowRequest$Type extends MessageType<PostProcessArrowRequest> {
    constructor() {
        super("sil.PostProcessArrowRequest", [
            { no: 1, name: "run_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<PostProcessArrowRequest>): PostProcessArrowRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.runId = "";
        if (value !== undefined)
            reflectionMergePartial<PostProcessArrowRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PostProcessArrowRequest): PostProcessArrowRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string run_id */ 1:
                    message.runId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PostProcessArrowRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string run_id = 1; */
        if (message.runId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.runId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message sil.PostProcessArrowRequest
 */
export const PostProcessArrowRequest = new PostProcessArrowRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PostProcessArrowResponse$Type extends MessageType<PostProcessArrowResponse> {
    constructor() {
        super("sil.PostProcessArrowResponse", [
            { no: 1, name: "arrow_path", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<PostProcessArrowResponse>): PostProcessArrowResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.arrowPath = "";
        if (value !== undefined)
            reflectionMergePartial<PostProcessArrowResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PostProcessArrowResponse): PostProcessArrowResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string arrow_path */ 1:
                    message.arrowPath = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PostProcessArrowResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string arrow_path = 1; */
        if (message.arrowPath !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.arrowPath);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message sil.PostProcessArrowResponse
 */
export const PostProcessArrowResponse = new PostProcessArrowResponse$Type();
/**
 * @generated ServiceType for protobuf service sil.ExportEvidenceService
 */
export const ExportEvidenceService = new ServiceType("sil.ExportEvidenceService", [
    { name: "PackMarzip", options: {}, I: PackMarzipRequest, O: PackMarzipResponse },
    { name: "PostProcessArrow", options: {}, I: PostProcessArrowRequest, O: PostProcessArrowResponse }
]);
