// @generated by protobuf-ts 2.11.1 with parameter generate_dependencies
// @generated from protobuf file "sil/lifecycle_control.proto" (package "sil", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { LifecycleControlService } from "./lifecycle_control";
import type { CleanupResponse } from "./lifecycle_control";
import type { CleanupRequest } from "./lifecycle_control";
import type { DeactivateResponse } from "./lifecycle_control";
import type { DeactivateRequest } from "./lifecycle_control";
import type { ActivateResponse } from "./lifecycle_control";
import type { ActivateRequest } from "./lifecycle_control";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { ConfigureResponse } from "./lifecycle_control";
import type { ConfigureRequest } from "./lifecycle_control";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service sil.LifecycleControlService
 */
export interface ILifecycleControlServiceClient {
    /**
     * @generated from protobuf rpc: Configure
     */
    configure(input: ConfigureRequest, options?: RpcOptions): UnaryCall<ConfigureRequest, ConfigureResponse>;
    /**
     * @generated from protobuf rpc: Activate
     */
    activate(input: ActivateRequest, options?: RpcOptions): UnaryCall<ActivateRequest, ActivateResponse>;
    /**
     * @generated from protobuf rpc: Deactivate
     */
    deactivate(input: DeactivateRequest, options?: RpcOptions): UnaryCall<DeactivateRequest, DeactivateResponse>;
    /**
     * @generated from protobuf rpc: Cleanup
     */
    cleanup(input: CleanupRequest, options?: RpcOptions): UnaryCall<CleanupRequest, CleanupResponse>;
}
/**
 * @generated from protobuf service sil.LifecycleControlService
 */
export class LifecycleControlServiceClient implements ILifecycleControlServiceClient, ServiceInfo {
    typeName = LifecycleControlService.typeName;
    methods = LifecycleControlService.methods;
    options = LifecycleControlService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: Configure
     */
    configure(input: ConfigureRequest, options?: RpcOptions): UnaryCall<ConfigureRequest, ConfigureResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<ConfigureRequest, ConfigureResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Activate
     */
    activate(input: ActivateRequest, options?: RpcOptions): UnaryCall<ActivateRequest, ActivateResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<ActivateRequest, ActivateResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Deactivate
     */
    deactivate(input: DeactivateRequest, options?: RpcOptions): UnaryCall<DeactivateRequest, DeactivateResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeactivateRequest, DeactivateResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Cleanup
     */
    cleanup(input: CleanupRequest, options?: RpcOptions): UnaryCall<CleanupRequest, CleanupResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<CleanupRequest, CleanupResponse>("unary", this._transport, method, opt, input);
    }
}
