// @generated by protobuf-ts 2.11.1 with parameter generate_dependencies
// @generated from protobuf file "sil/module_pulse.proto" (package "sil", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Timestamp } from "../google/protobuf/timestamp";
/**
 * @generated from protobuf message sil.ModulePulse
 */
export interface ModulePulse {
    /**
     * @generated from protobuf field: google.protobuf.Timestamp stamp = 1
     */
    stamp?: Timestamp;
    /**
     * @generated from protobuf field: sil.ModulePulse.ModuleId module_id = 2
     */
    moduleId: ModulePulse_ModuleId;
    /**
     * @generated from protobuf field: sil.ModulePulse.HealthState state = 3
     */
    state: ModulePulse_HealthState;
    /**
     * @generated from protobuf field: uint32 latency_ms = 4
     */
    latencyMs: number;
    /**
     * @generated from protobuf field: uint32 message_drops = 5
     */
    messageDrops: number;
}
/**
 * @generated from protobuf enum sil.ModulePulse.ModuleId
 */
export enum ModulePulse_ModuleId {
    /**
     * @generated from protobuf enum value: MODULE_ID_UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: MODULE_ID_M1 = 1;
     */
    M1 = 1,
    /**
     * @generated from protobuf enum value: MODULE_ID_M2 = 2;
     */
    M2 = 2,
    /**
     * @generated from protobuf enum value: MODULE_ID_M3 = 3;
     */
    M3 = 3,
    /**
     * @generated from protobuf enum value: MODULE_ID_M4 = 4;
     */
    M4 = 4,
    /**
     * @generated from protobuf enum value: MODULE_ID_M5 = 5;
     */
    M5 = 5,
    /**
     * @generated from protobuf enum value: MODULE_ID_M6 = 6;
     */
    M6 = 6,
    /**
     * @generated from protobuf enum value: MODULE_ID_M7 = 7;
     */
    M7 = 7,
    /**
     * @generated from protobuf enum value: MODULE_ID_M8 = 8;
     */
    M8 = 8
}
/**
 * @generated from protobuf enum sil.ModulePulse.HealthState
 */
export enum ModulePulse_HealthState {
    /**
     * @generated from protobuf enum value: HEALTH_STATE_UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: HEALTH_STATE_GREEN = 1;
     */
    GREEN = 1,
    /**
     * @generated from protobuf enum value: HEALTH_STATE_AMBER = 2;
     */
    AMBER = 2,
    /**
     * @generated from protobuf enum value: HEALTH_STATE_RED = 3;
     */
    RED = 3
}
// @generated message type with reflection information, may provide speed optimized methods
class ModulePulse$Type extends MessageType<ModulePulse> {
    constructor() {
        super("sil.ModulePulse", [
            { no: 1, name: "stamp", kind: "message", T: () => Timestamp },
            { no: 2, name: "module_id", kind: "enum", T: () => ["sil.ModulePulse.ModuleId", ModulePulse_ModuleId, "MODULE_ID_"] },
            { no: 3, name: "state", kind: "enum", T: () => ["sil.ModulePulse.HealthState", ModulePulse_HealthState, "HEALTH_STATE_"] },
            { no: 4, name: "latency_ms", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 5, name: "message_drops", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
    create(value?: PartialMessage<ModulePulse>): ModulePulse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.moduleId = 0;
        message.state = 0;
        message.latencyMs = 0;
        message.messageDrops = 0;
        if (value !== undefined)
            reflectionMergePartial<ModulePulse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ModulePulse): ModulePulse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* google.protobuf.Timestamp stamp */ 1:
                    message.stamp = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.stamp);
                    break;
                case /* sil.ModulePulse.ModuleId module_id */ 2:
                    message.moduleId = reader.int32();
                    break;
                case /* sil.ModulePulse.HealthState state */ 3:
                    message.state = reader.int32();
                    break;
                case /* uint32 latency_ms */ 4:
                    message.latencyMs = reader.uint32();
                    break;
                case /* uint32 message_drops */ 5:
                    message.messageDrops = reader.uint32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ModulePulse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* google.protobuf.Timestamp stamp = 1; */
        if (message.stamp)
            Timestamp.internalBinaryWrite(message.stamp, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* sil.ModulePulse.ModuleId module_id = 2; */
        if (message.moduleId !== 0)
            writer.tag(2, WireType.Varint).int32(message.moduleId);
        /* sil.ModulePulse.HealthState state = 3; */
        if (message.state !== 0)
            writer.tag(3, WireType.Varint).int32(message.state);
        /* uint32 latency_ms = 4; */
        if (message.latencyMs !== 0)
            writer.tag(4, WireType.Varint).uint32(message.latencyMs);
        /* uint32 message_drops = 5; */
        if (message.messageDrops !== 0)
            writer.tag(5, WireType.Varint).uint32(message.messageDrops);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message sil.ModulePulse
 */
export const ModulePulse = new ModulePulse$Type();
