// @generated by protobuf-ts 2.11.1 with parameter generate_dependencies
// @generated from protobuf file "sil/radar_measurement.proto" (package "sil", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Timestamp } from "../google/protobuf/timestamp";
/**
 * @generated from protobuf message sil.RadarMeasurement
 */
export interface RadarMeasurement {
    /**
     * @generated from protobuf field: google.protobuf.Timestamp stamp = 1
     */
    stamp?: Timestamp;
    /**
     * @generated from protobuf field: repeated sil.RadarMeasurement.PolarTarget polar_targets = 2
     */
    polarTargets: RadarMeasurement_PolarTarget[];
    /**
     * @generated from protobuf field: uint32 clutter_cardinality = 3
     */
    clutterCardinality: number;
}
/**
 * @generated from protobuf message sil.RadarMeasurement.PolarTarget
 */
export interface RadarMeasurement_PolarTarget {
    /**
     * @generated from protobuf field: double range = 1
     */
    range: number;
    /**
     * @generated from protobuf field: double bearing = 2
     */
    bearing: number;
    /**
     * @generated from protobuf field: double rcs = 3
     */
    rcs: number;
}
// @generated message type with reflection information, may provide speed optimized methods
class RadarMeasurement$Type extends MessageType<RadarMeasurement> {
    constructor() {
        super("sil.RadarMeasurement", [
            { no: 1, name: "stamp", kind: "message", T: () => Timestamp },
            { no: 2, name: "polar_targets", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => RadarMeasurement_PolarTarget },
            { no: 3, name: "clutter_cardinality", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
    create(value?: PartialMessage<RadarMeasurement>): RadarMeasurement {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.polarTargets = [];
        message.clutterCardinality = 0;
        if (value !== undefined)
            reflectionMergePartial<RadarMeasurement>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RadarMeasurement): RadarMeasurement {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* google.protobuf.Timestamp stamp */ 1:
                    message.stamp = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.stamp);
                    break;
                case /* repeated sil.RadarMeasurement.PolarTarget polar_targets */ 2:
                    message.polarTargets.push(RadarMeasurement_PolarTarget.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* uint32 clutter_cardinality */ 3:
                    message.clutterCardinality = reader.uint32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RadarMeasurement, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* google.protobuf.Timestamp stamp = 1; */
        if (message.stamp)
            Timestamp.internalBinaryWrite(message.stamp, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* repeated sil.RadarMeasurement.PolarTarget polar_targets = 2; */
        for (let i = 0; i < message.polarTargets.length; i++)
            RadarMeasurement_PolarTarget.internalBinaryWrite(message.polarTargets[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* uint32 clutter_cardinality = 3; */
        if (message.clutterCardinality !== 0)
            writer.tag(3, WireType.Varint).uint32(message.clutterCardinality);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message sil.RadarMeasurement
 */
export const RadarMeasurement = new RadarMeasurement$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RadarMeasurement_PolarTarget$Type extends MessageType<RadarMeasurement_PolarTarget> {
    constructor() {
        super("sil.RadarMeasurement.PolarTarget", [
            { no: 1, name: "range", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 2, name: "bearing", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 3, name: "rcs", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ }
        ]);
    }
    create(value?: PartialMessage<RadarMeasurement_PolarTarget>): RadarMeasurement_PolarTarget {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.range = 0;
        message.bearing = 0;
        message.rcs = 0;
        if (value !== undefined)
            reflectionMergePartial<RadarMeasurement_PolarTarget>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RadarMeasurement_PolarTarget): RadarMeasurement_PolarTarget {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* double range */ 1:
                    message.range = reader.double();
                    break;
                case /* double bearing */ 2:
                    message.bearing = reader.double();
                    break;
                case /* double rcs */ 3:
                    message.rcs = reader.double();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RadarMeasurement_PolarTarget, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* double range = 1; */
        if (message.range !== 0)
            writer.tag(1, WireType.Bit64).double(message.range);
        /* double bearing = 2; */
        if (message.bearing !== 0)
            writer.tag(2, WireType.Bit64).double(message.bearing);
        /* double rcs = 3; */
        if (message.rcs !== 0)
            writer.tag(3, WireType.Bit64).double(message.rcs);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message sil.RadarMeasurement.PolarTarget
 */
export const RadarMeasurement_PolarTarget = new RadarMeasurement_PolarTarget$Type();
