// @generated by protobuf-ts 2.11.1 with parameter generate_dependencies
// @generated from protobuf file "sil/self_check.proto" (package "sil", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { ModulePulse } from "./module_pulse";
/**
 * @generated from protobuf message sil.ProbeRequest
 */
export interface ProbeRequest {
}
/**
 * @generated from protobuf message sil.ProbeResponse
 */
export interface ProbeResponse {
    /**
     * @generated from protobuf field: bool all_clear = 1
     */
    allClear: boolean;
    /**
     * @generated from protobuf field: repeated sil.CheckItem items = 2
     */
    items: CheckItem[];
}
/**
 * @generated from protobuf message sil.CheckItem
 */
export interface CheckItem {
    /**
     * @generated from protobuf field: string name = 1
     */
    name: string;
    /**
     * @generated from protobuf field: bool passed = 2
     */
    passed: boolean;
    /**
     * @generated from protobuf field: string detail = 3
     */
    detail: string;
}
/**
 * @generated from protobuf message sil.StatusRequest
 */
export interface StatusRequest {
}
/**
 * @generated from protobuf message sil.StatusResponse
 */
export interface StatusResponse {
    /**
     * @generated from protobuf field: repeated sil.ModulePulse module_pulses = 1
     */
    modulePulses: ModulePulse[];
}
// @generated message type with reflection information, may provide speed optimized methods
class ProbeRequest$Type extends MessageType<ProbeRequest> {
    constructor() {
        super("sil.ProbeRequest", []);
    }
    create(value?: PartialMessage<ProbeRequest>): ProbeRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<ProbeRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ProbeRequest): ProbeRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ProbeRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message sil.ProbeRequest
 */
export const ProbeRequest = new ProbeRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ProbeResponse$Type extends MessageType<ProbeResponse> {
    constructor() {
        super("sil.ProbeResponse", [
            { no: 1, name: "all_clear", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "items", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => CheckItem }
        ]);
    }
    create(value?: PartialMessage<ProbeResponse>): ProbeResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.allClear = false;
        message.items = [];
        if (value !== undefined)
            reflectionMergePartial<ProbeResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ProbeResponse): ProbeResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool all_clear */ 1:
                    message.allClear = reader.bool();
                    break;
                case /* repeated sil.CheckItem items */ 2:
                    message.items.push(CheckItem.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ProbeResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool all_clear = 1; */
        if (message.allClear !== false)
            writer.tag(1, WireType.Varint).bool(message.allClear);
        /* repeated sil.CheckItem items = 2; */
        for (let i = 0; i < message.items.length; i++)
            CheckItem.internalBinaryWrite(message.items[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message sil.ProbeResponse
 */
export const ProbeResponse = new ProbeResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CheckItem$Type extends MessageType<CheckItem> {
    constructor() {
        super("sil.CheckItem", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "passed", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 3, name: "detail", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<CheckItem>): CheckItem {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.name = "";
        message.passed = false;
        message.detail = "";
        if (value !== undefined)
            reflectionMergePartial<CheckItem>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CheckItem): CheckItem {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string name */ 1:
                    message.name = reader.string();
                    break;
                case /* bool passed */ 2:
                    message.passed = reader.bool();
                    break;
                case /* string detail */ 3:
                    message.detail = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CheckItem, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string name = 1; */
        if (message.name !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.name);
        /* bool passed = 2; */
        if (message.passed !== false)
            writer.tag(2, WireType.Varint).bool(message.passed);
        /* string detail = 3; */
        if (message.detail !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.detail);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message sil.CheckItem
 */
export const CheckItem = new CheckItem$Type();
// @generated message type with reflection information, may provide speed optimized methods
class StatusRequest$Type extends MessageType<StatusRequest> {
    constructor() {
        super("sil.StatusRequest", []);
    }
    create(value?: PartialMessage<StatusRequest>): StatusRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<StatusRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: StatusRequest): StatusRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: StatusRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message sil.StatusRequest
 */
export const StatusRequest = new StatusRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class StatusResponse$Type extends MessageType<StatusResponse> {
    constructor() {
        super("sil.StatusResponse", [
            { no: 1, name: "module_pulses", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => ModulePulse }
        ]);
    }
    create(value?: PartialMessage<StatusResponse>): StatusResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.modulePulses = [];
        if (value !== undefined)
            reflectionMergePartial<StatusResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: StatusResponse): StatusResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated sil.ModulePulse module_pulses */ 1:
                    message.modulePulses.push(ModulePulse.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: StatusResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated sil.ModulePulse module_pulses = 1; */
        for (let i = 0; i < message.modulePulses.length; i++)
            ModulePulse.internalBinaryWrite(message.modulePulses[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message sil.StatusResponse
 */
export const StatusResponse = new StatusResponse$Type();
/**
 * @generated ServiceType for protobuf service sil.SelfCheckService
 */
export const SelfCheckService = new ServiceType("sil.SelfCheckService", [
    { name: "Probe", options: {}, I: ProbeRequest, O: ProbeResponse },
    { name: "Status", options: {}, I: StatusRequest, O: StatusResponse }
]);
