// @generated by protobuf-ts 2.11.1 with parameter generate_dependencies
// @generated from protobuf file "sil/self_check.proto" (package "sil", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { SelfCheckService } from "./self_check";
import type { StatusResponse } from "./self_check";
import type { StatusRequest } from "./self_check";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { ProbeResponse } from "./self_check";
import type { ProbeRequest } from "./self_check";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service sil.SelfCheckService
 */
export interface ISelfCheckServiceClient {
    /**
     * @generated from protobuf rpc: Probe
     */
    probe(input: ProbeRequest, options?: RpcOptions): UnaryCall<ProbeRequest, ProbeResponse>;
    /**
     * @generated from protobuf rpc: Status
     */
    status(input: StatusRequest, options?: RpcOptions): UnaryCall<StatusRequest, StatusResponse>;
}
/**
 * @generated from protobuf service sil.SelfCheckService
 */
export class SelfCheckServiceClient implements ISelfCheckServiceClient, ServiceInfo {
    typeName = SelfCheckService.typeName;
    methods = SelfCheckService.methods;
    options = SelfCheckService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: Probe
     */
    probe(input: ProbeRequest, options?: RpcOptions): UnaryCall<ProbeRequest, ProbeResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<ProbeRequest, ProbeResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Status
     */
    status(input: StatusRequest, options?: RpcOptions): UnaryCall<StatusRequest, StatusResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<StatusRequest, StatusResponse>("unary", this._transport, method, opt, input);
    }
}
