// @generated by protobuf-ts 2.11.1 with parameter generate_dependencies
// @generated from protobuf file "sil/sim_clock.proto" (package "sil", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { SimClockService } from "./sim_clock";
import type { GetTimeResponse } from "./sim_clock";
import type { GetTimeRequest } from "./sim_clock";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { SetRateResponse } from "./sim_clock";
import type { SetRateRequest } from "./sim_clock";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service sil.SimClockService
 */
export interface ISimClockServiceClient {
    /**
     * @generated from protobuf rpc: SetRate
     */
    setRate(input: SetRateRequest, options?: RpcOptions): UnaryCall<SetRateRequest, SetRateResponse>;
    /**
     * @generated from protobuf rpc: GetTime
     */
    getTime(input: GetTimeRequest, options?: RpcOptions): UnaryCall<GetTimeRequest, GetTimeResponse>;
}
/**
 * @generated from protobuf service sil.SimClockService
 */
export class SimClockServiceClient implements ISimClockServiceClient, ServiceInfo {
    typeName = SimClockService.typeName;
    methods = SimClockService.methods;
    options = SimClockService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: SetRate
     */
    setRate(input: SetRateRequest, options?: RpcOptions): UnaryCall<SetRateRequest, SetRateResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<SetRateRequest, SetRateResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetTime
     */
    getTime(input: GetTimeRequest, options?: RpcOptions): UnaryCall<GetTimeRequest, GetTimeResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetTimeRequest, GetTimeResponse>("unary", this._transport, method, opt, input);
    }
}
