// @generated by protobuf-ts 2.11.1 with parameter generate_dependencies
// @generated from protobuf file "sil/target_vessel_state.proto" (package "sil", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Timestamp } from "../google/protobuf/timestamp";
/**
 * @generated from protobuf message sil.TargetVesselState
 */
export interface TargetVesselState {
    /**
     * @generated from protobuf field: google.protobuf.Timestamp stamp = 1
     */
    stamp?: Timestamp;
    /**
     * @generated from protobuf field: uint32 mmsi = 2
     */
    mmsi: number;
    /**
     * @generated from protobuf field: sil.TargetVesselState.Pose pose = 3
     */
    pose?: TargetVesselState_Pose;
    /**
     * @generated from protobuf field: sil.TargetVesselState.Kinematics kinematics = 4
     */
    kinematics?: TargetVesselState_Kinematics;
    /**
     * @generated from protobuf field: sil.TargetVesselState.ShipType ship_type = 5
     */
    shipType: TargetVesselState_ShipType;
    /**
     * @generated from protobuf field: sil.TargetVesselState.TargetMode mode = 6
     */
    mode: TargetVesselState_TargetMode;
}
/**
 * @generated from protobuf message sil.TargetVesselState.Pose
 */
export interface TargetVesselState_Pose {
    /**
     * @generated from protobuf field: double lat = 1
     */
    lat: number;
    /**
     * @generated from protobuf field: double lon = 2
     */
    lon: number;
    /**
     * @generated from protobuf field: double heading = 3
     */
    heading: number;
}
/**
 * @generated from protobuf message sil.TargetVesselState.Kinematics
 */
export interface TargetVesselState_Kinematics {
    /**
     * @generated from protobuf field: double sog = 1
     */
    sog: number;
    /**
     * @generated from protobuf field: double cog = 2
     */
    cog: number;
    /**
     * @generated from protobuf field: double rot = 3
     */
    rot: number;
}
/**
 * @generated from protobuf enum sil.TargetVesselState.ShipType
 */
export enum TargetVesselState_ShipType {
    /**
     * @generated from protobuf enum value: SHIP_TYPE_UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: SHIP_TYPE_CARGO = 1;
     */
    CARGO = 1,
    /**
     * @generated from protobuf enum value: SHIP_TYPE_TANKER = 2;
     */
    TANKER = 2,
    /**
     * @generated from protobuf enum value: SHIP_TYPE_PASSENGER = 3;
     */
    PASSENGER = 3,
    /**
     * @generated from protobuf enum value: SHIP_TYPE_FISHING = 4;
     */
    FISHING = 4,
    /**
     * @generated from protobuf enum value: SHIP_TYPE_TUG = 5;
     */
    TUG = 5,
    /**
     * @generated from protobuf enum value: SHIP_TYPE_PLEASURE = 6;
     */
    PLEASURE = 6
}
/**
 * @generated from protobuf enum sil.TargetVesselState.TargetMode
 */
export enum TargetVesselState_TargetMode {
    /**
     * @generated from protobuf enum value: TARGET_MODE_UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: TARGET_MODE_REPLAY = 1;
     */
    REPLAY = 1,
    /**
     * @generated from protobuf enum value: TARGET_MODE_NCDM = 2;
     */
    NCDM = 2,
    /**
     * @generated from protobuf enum value: TARGET_MODE_INTELLIGENT = 3;
     */
    INTELLIGENT = 3
}
// @generated message type with reflection information, may provide speed optimized methods
class TargetVesselState$Type extends MessageType<TargetVesselState> {
    constructor() {
        super("sil.TargetVesselState", [
            { no: 1, name: "stamp", kind: "message", T: () => Timestamp },
            { no: 2, name: "mmsi", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 3, name: "pose", kind: "message", T: () => TargetVesselState_Pose },
            { no: 4, name: "kinematics", kind: "message", T: () => TargetVesselState_Kinematics },
            { no: 5, name: "ship_type", kind: "enum", T: () => ["sil.TargetVesselState.ShipType", TargetVesselState_ShipType, "SHIP_TYPE_"] },
            { no: 6, name: "mode", kind: "enum", T: () => ["sil.TargetVesselState.TargetMode", TargetVesselState_TargetMode, "TARGET_MODE_"] }
        ]);
    }
    create(value?: PartialMessage<TargetVesselState>): TargetVesselState {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.mmsi = 0;
        message.shipType = 0;
        message.mode = 0;
        if (value !== undefined)
            reflectionMergePartial<TargetVesselState>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TargetVesselState): TargetVesselState {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* google.protobuf.Timestamp stamp */ 1:
                    message.stamp = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.stamp);
                    break;
                case /* uint32 mmsi */ 2:
                    message.mmsi = reader.uint32();
                    break;
                case /* sil.TargetVesselState.Pose pose */ 3:
                    message.pose = TargetVesselState_Pose.internalBinaryRead(reader, reader.uint32(), options, message.pose);
                    break;
                case /* sil.TargetVesselState.Kinematics kinematics */ 4:
                    message.kinematics = TargetVesselState_Kinematics.internalBinaryRead(reader, reader.uint32(), options, message.kinematics);
                    break;
                case /* sil.TargetVesselState.ShipType ship_type */ 5:
                    message.shipType = reader.int32();
                    break;
                case /* sil.TargetVesselState.TargetMode mode */ 6:
                    message.mode = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TargetVesselState, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* google.protobuf.Timestamp stamp = 1; */
        if (message.stamp)
            Timestamp.internalBinaryWrite(message.stamp, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* uint32 mmsi = 2; */
        if (message.mmsi !== 0)
            writer.tag(2, WireType.Varint).uint32(message.mmsi);
        /* sil.TargetVesselState.Pose pose = 3; */
        if (message.pose)
            TargetVesselState_Pose.internalBinaryWrite(message.pose, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* sil.TargetVesselState.Kinematics kinematics = 4; */
        if (message.kinematics)
            TargetVesselState_Kinematics.internalBinaryWrite(message.kinematics, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* sil.TargetVesselState.ShipType ship_type = 5; */
        if (message.shipType !== 0)
            writer.tag(5, WireType.Varint).int32(message.shipType);
        /* sil.TargetVesselState.TargetMode mode = 6; */
        if (message.mode !== 0)
            writer.tag(6, WireType.Varint).int32(message.mode);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message sil.TargetVesselState
 */
export const TargetVesselState = new TargetVesselState$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TargetVesselState_Pose$Type extends MessageType<TargetVesselState_Pose> {
    constructor() {
        super("sil.TargetVesselState.Pose", [
            { no: 1, name: "lat", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 2, name: "lon", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 3, name: "heading", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ }
        ]);
    }
    create(value?: PartialMessage<TargetVesselState_Pose>): TargetVesselState_Pose {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.lat = 0;
        message.lon = 0;
        message.heading = 0;
        if (value !== undefined)
            reflectionMergePartial<TargetVesselState_Pose>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TargetVesselState_Pose): TargetVesselState_Pose {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* double lat */ 1:
                    message.lat = reader.double();
                    break;
                case /* double lon */ 2:
                    message.lon = reader.double();
                    break;
                case /* double heading */ 3:
                    message.heading = reader.double();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TargetVesselState_Pose, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* double lat = 1; */
        if (message.lat !== 0)
            writer.tag(1, WireType.Bit64).double(message.lat);
        /* double lon = 2; */
        if (message.lon !== 0)
            writer.tag(2, WireType.Bit64).double(message.lon);
        /* double heading = 3; */
        if (message.heading !== 0)
            writer.tag(3, WireType.Bit64).double(message.heading);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message sil.TargetVesselState.Pose
 */
export const TargetVesselState_Pose = new TargetVesselState_Pose$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TargetVesselState_Kinematics$Type extends MessageType<TargetVesselState_Kinematics> {
    constructor() {
        super("sil.TargetVesselState.Kinematics", [
            { no: 1, name: "sog", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 2, name: "cog", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 3, name: "rot", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ }
        ]);
    }
    create(value?: PartialMessage<TargetVesselState_Kinematics>): TargetVesselState_Kinematics {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.sog = 0;
        message.cog = 0;
        message.rot = 0;
        if (value !== undefined)
            reflectionMergePartial<TargetVesselState_Kinematics>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TargetVesselState_Kinematics): TargetVesselState_Kinematics {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* double sog */ 1:
                    message.sog = reader.double();
                    break;
                case /* double cog */ 2:
                    message.cog = reader.double();
                    break;
                case /* double rot */ 3:
                    message.rot = reader.double();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TargetVesselState_Kinematics, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* double sog = 1; */
        if (message.sog !== 0)
            writer.tag(1, WireType.Bit64).double(message.sog);
        /* double cog = 2; */
        if (message.cog !== 0)
            writer.tag(2, WireType.Bit64).double(message.cog);
        /* double rot = 3; */
        if (message.rot !== 0)
            writer.tag(3, WireType.Bit64).double(message.rot);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message sil.TargetVesselState.Kinematics
 */
export const TargetVesselState_Kinematics = new TargetVesselState_Kinematics$Type();
