# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sil/asdr_event.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sil/asdr_event.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14sil/asdr_event.proto\x12\x03sil\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8a\x02\n\tASDREvent\x12)\n\x05stamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x12\n\nevent_type\x18\x02 \x01(\t\x12\x10\n\x08rule_ref\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65\x63ision_id\x18\x04 \x01(\t\x12\'\n\x07verdict\x18\x05 \x01(\x0e\x32\x16.sil.ASDREvent.Verdict\x12\x14\n\x0cpayload_json\x18\x06 \x01(\t\"X\n\x07Verdict\x12\x17\n\x13VERDICT_UNSPECIFIED\x10\x00\x12\x10\n\x0cVERDICT_PASS\x10\x01\x12\x10\n\x0cVERDICT_RISK\x10\x02\x12\x10\n\x0cVERDICT_FAIL\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sil.asdr_event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ASDREVENT']._serialized_start=63
  _globals['_ASDREVENT']._serialized_end=329
  _globals['_ASDREVENT_VERDICT']._serialized_start=241
  _globals['_ASDREVENT_VERDICT']._serialized_end=329
# @@protoc_insertion_point(module_scope)
