# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sil/environment_state.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sil/environment_state.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bsil/environment_state.proto\x12\x03sil\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa9\x02\n\x10\x45nvironmentState\x12)\n\x05stamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12(\n\x04wind\x18\x02 \x01(\x0b\x32\x1a.sil.EnvironmentState.Wind\x12.\n\x07\x63urrent\x18\x03 \x01(\x0b\x32\x1d.sil.EnvironmentState.Current\x12\x15\n\rvisibility_nm\x18\x04 \x01(\x01\x12\x1a\n\x12sea_state_beaufort\x18\x05 \x01(\r\x1a,\n\x04Wind\x12\x11\n\tdirection\x18\x01 \x01(\x01\x12\x11\n\tspeed_mps\x18\x02 \x01(\x01\x1a/\n\x07\x43urrent\x12\x11\n\tdirection\x18\x01 \x01(\x01\x12\x11\n\tspeed_mps\x18\x02 \x01(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sil.environment_state_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENVIRONMENTSTATE']._serialized_start=70
  _globals['_ENVIRONMENTSTATE']._serialized_end=367
  _globals['_ENVIRONMENTSTATE_WIND']._serialized_start=274
  _globals['_ENVIRONMENTSTATE_WIND']._serialized_end=318
  _globals['_ENVIRONMENTSTATE_CURRENT']._serialized_start=320
  _globals['_ENVIRONMENTSTATE_CURRENT']._serialized_end=367
# @@protoc_insertion_point(module_scope)
