# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sil/export_evidence.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sil/export_evidence.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19sil/export_evidence.proto\x12\x03sil\"#\n\x11PackMarzipRequest\x12\x0e\n\x06run_id\x18\x01 \x01(\t\":\n\x12PackMarzipResponse\x12\x14\n\x0c\x64ownload_url\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\")\n\x17PostProcessArrowRequest\x12\x0e\n\x06run_id\x18\x01 \x01(\t\".\n\x18PostProcessArrowResponse\x12\x12\n\narrow_path\x18\x01 \x01(\t2\xa7\x01\n\x15\x45xportEvidenceService\x12=\n\nPackMarzip\x12\x16.sil.PackMarzipRequest\x1a\x17.sil.PackMarzipResponse\x12O\n\x10PostProcessArrow\x12\x1c.sil.PostProcessArrowRequest\x1a\x1d.sil.PostProcessArrowResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sil.export_evidence_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PACKMARZIPREQUEST']._serialized_start=34
  _globals['_PACKMARZIPREQUEST']._serialized_end=69
  _globals['_PACKMARZIPRESPONSE']._serialized_start=71
  _globals['_PACKMARZIPRESPONSE']._serialized_end=129
  _globals['_POSTPROCESSARROWREQUEST']._serialized_start=131
  _globals['_POSTPROCESSARROWREQUEST']._serialized_end=172
  _globals['_POSTPROCESSARROWRESPONSE']._serialized_start=174
  _globals['_POSTPROCESSARROWRESPONSE']._serialized_end=220
  _globals['_EXPORTEVIDENCESERVICE']._serialized_start=223
  _globals['_EXPORTEVIDENCESERVICE']._serialized_end=390
# @@protoc_insertion_point(module_scope)
