# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import export_evidence_pb2 as sil_dot_export__evidence__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sil/export_evidence_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ExportEvidenceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PackMarzip = channel.unary_unary(
                '/sil.ExportEvidenceService/PackMarzip',
                request_serializer=sil_dot_export__evidence__pb2.PackMarzipRequest.SerializeToString,
                response_deserializer=sil_dot_export__evidence__pb2.PackMarzipResponse.FromString,
                _registered_method=True)
        self.PostProcessArrow = channel.unary_unary(
                '/sil.ExportEvidenceService/PostProcessArrow',
                request_serializer=sil_dot_export__evidence__pb2.PostProcessArrowRequest.SerializeToString,
                response_deserializer=sil_dot_export__evidence__pb2.PostProcessArrowResponse.FromString,
                _registered_method=True)


class ExportEvidenceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PackMarzip(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PostProcessArrow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExportEvidenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PackMarzip': grpc.unary_unary_rpc_method_handler(
                    servicer.PackMarzip,
                    request_deserializer=sil_dot_export__evidence__pb2.PackMarzipRequest.FromString,
                    response_serializer=sil_dot_export__evidence__pb2.PackMarzipResponse.SerializeToString,
            ),
            'PostProcessArrow': grpc.unary_unary_rpc_method_handler(
                    servicer.PostProcessArrow,
                    request_deserializer=sil_dot_export__evidence__pb2.PostProcessArrowRequest.FromString,
                    response_serializer=sil_dot_export__evidence__pb2.PostProcessArrowResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sil.ExportEvidenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sil.ExportEvidenceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ExportEvidenceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PackMarzip(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sil.ExportEvidenceService/PackMarzip',
            sil_dot_export__evidence__pb2.PackMarzipRequest.SerializeToString,
            sil_dot_export__evidence__pb2.PackMarzipResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PostProcessArrow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sil.ExportEvidenceService/PostProcessArrow',
            sil_dot_export__evidence__pb2.PostProcessArrowRequest.SerializeToString,
            sil_dot_export__evidence__pb2.PostProcessArrowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
