# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import fault_trigger_pb2 as sil_dot_fault__trigger__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sil/fault_trigger_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FaultTriggerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Trigger = channel.unary_unary(
                '/sil.FaultTriggerService/Trigger',
                request_serializer=sil_dot_fault__trigger__pb2.TriggerRequest.SerializeToString,
                response_deserializer=sil_dot_fault__trigger__pb2.TriggerResponse.FromString,
                _registered_method=True)
        self.ListFaults = channel.unary_unary(
                '/sil.FaultTriggerService/ListFaults',
                request_serializer=sil_dot_fault__trigger__pb2.ListFaultsRequest.SerializeToString,
                response_deserializer=sil_dot_fault__trigger__pb2.ListFaultsResponse.FromString,
                _registered_method=True)
        self.Cancel = channel.unary_unary(
                '/sil.FaultTriggerService/Cancel',
                request_serializer=sil_dot_fault__trigger__pb2.CancelRequest.SerializeToString,
                response_deserializer=sil_dot_fault__trigger__pb2.CancelResponse.FromString,
                _registered_method=True)


class FaultTriggerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Trigger(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFaults(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cancel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FaultTriggerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Trigger': grpc.unary_unary_rpc_method_handler(
                    servicer.Trigger,
                    request_deserializer=sil_dot_fault__trigger__pb2.TriggerRequest.FromString,
                    response_serializer=sil_dot_fault__trigger__pb2.TriggerResponse.SerializeToString,
            ),
            'ListFaults': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFaults,
                    request_deserializer=sil_dot_fault__trigger__pb2.ListFaultsRequest.FromString,
                    response_serializer=sil_dot_fault__trigger__pb2.ListFaultsResponse.SerializeToString,
            ),
            'Cancel': grpc.unary_unary_rpc_method_handler(
                    servicer.Cancel,
                    request_deserializer=sil_dot_fault__trigger__pb2.CancelRequest.FromString,
                    response_serializer=sil_dot_fault__trigger__pb2.CancelResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sil.FaultTriggerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sil.FaultTriggerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FaultTriggerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Trigger(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sil.FaultTriggerService/Trigger',
            sil_dot_fault__trigger__pb2.TriggerRequest.SerializeToString,
            sil_dot_fault__trigger__pb2.TriggerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFaults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sil.FaultTriggerService/ListFaults',
            sil_dot_fault__trigger__pb2.ListFaultsRequest.SerializeToString,
            sil_dot_fault__trigger__pb2.ListFaultsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Cancel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sil.FaultTriggerService/Cancel',
            sil_dot_fault__trigger__pb2.CancelRequest.SerializeToString,
            sil_dot_fault__trigger__pb2.CancelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
