# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sil/fault_trigger.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sil/fault_trigger.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17sil/fault_trigger.proto\x12\x03sil\":\n\x0eTriggerRequest\x12\x12\n\nfault_type\x18\x01 \x01(\t\x12\x14\n\x0cpayload_json\x18\x02 \x01(\t\"#\n\x0fTriggerResponse\x12\x10\n\x08\x66\x61ult_id\x18\x01 \x01(\t\"\x13\n\x11ListFaultsRequest\"6\n\x12ListFaultsResponse\x12 \n\x06\x61\x63tive\x18\x01 \x03(\x0b\x32\x10.sil.ActiveFault\"B\n\x0b\x41\x63tiveFault\x12\x10\n\x08\x66\x61ult_id\x18\x01 \x01(\t\x12\x12\n\nfault_type\x18\x02 \x01(\t\x12\r\n\x05stamp\x18\x03 \x01(\t\"!\n\rCancelRequest\x12\x10\n\x08\x66\x61ult_id\x18\x01 \x01(\t\"!\n\x0e\x43\x61ncelResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xbd\x01\n\x13\x46\x61ultTriggerService\x12\x34\n\x07Trigger\x12\x13.sil.TriggerRequest\x1a\x14.sil.TriggerResponse\x12=\n\nListFaults\x12\x16.sil.ListFaultsRequest\x1a\x17.sil.ListFaultsResponse\x12\x31\n\x06\x43\x61ncel\x12\x12.sil.CancelRequest\x1a\x13.sil.CancelResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sil.fault_trigger_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRIGGERREQUEST']._serialized_start=32
  _globals['_TRIGGERREQUEST']._serialized_end=90
  _globals['_TRIGGERRESPONSE']._serialized_start=92
  _globals['_TRIGGERRESPONSE']._serialized_end=127
  _globals['_LISTFAULTSREQUEST']._serialized_start=129
  _globals['_LISTFAULTSREQUEST']._serialized_end=148
  _globals['_LISTFAULTSRESPONSE']._serialized_start=150
  _globals['_LISTFAULTSRESPONSE']._serialized_end=204
  _globals['_ACTIVEFAULT']._serialized_start=206
  _globals['_ACTIVEFAULT']._serialized_end=272
  _globals['_CANCELREQUEST']._serialized_start=274
  _globals['_CANCELREQUEST']._serialized_end=307
  _globals['_CANCELRESPONSE']._serialized_start=309
  _globals['_CANCELRESPONSE']._serialized_end=342
  _globals['_FAULTTRIGGERSERVICE']._serialized_start=345
  _globals['_FAULTTRIGGERSERVICE']._serialized_end=534
# @@protoc_insertion_point(module_scope)
