# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import lifecycle_control_pb2 as sil_dot_lifecycle__control__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sil/lifecycle_control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LifecycleControlServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Configure = channel.unary_unary(
                '/sil.LifecycleControlService/Configure',
                request_serializer=sil_dot_lifecycle__control__pb2.ConfigureRequest.SerializeToString,
                response_deserializer=sil_dot_lifecycle__control__pb2.ConfigureResponse.FromString,
                _registered_method=True)
        self.Activate = channel.unary_unary(
                '/sil.LifecycleControlService/Activate',
                request_serializer=sil_dot_lifecycle__control__pb2.ActivateRequest.SerializeToString,
                response_deserializer=sil_dot_lifecycle__control__pb2.ActivateResponse.FromString,
                _registered_method=True)
        self.Deactivate = channel.unary_unary(
                '/sil.LifecycleControlService/Deactivate',
                request_serializer=sil_dot_lifecycle__control__pb2.DeactivateRequest.SerializeToString,
                response_deserializer=sil_dot_lifecycle__control__pb2.DeactivateResponse.FromString,
                _registered_method=True)
        self.Cleanup = channel.unary_unary(
                '/sil.LifecycleControlService/Cleanup',
                request_serializer=sil_dot_lifecycle__control__pb2.CleanupRequest.SerializeToString,
                response_deserializer=sil_dot_lifecycle__control__pb2.CleanupResponse.FromString,
                _registered_method=True)


class LifecycleControlServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Configure(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Activate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Deactivate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cleanup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LifecycleControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Configure': grpc.unary_unary_rpc_method_handler(
                    servicer.Configure,
                    request_deserializer=sil_dot_lifecycle__control__pb2.ConfigureRequest.FromString,
                    response_serializer=sil_dot_lifecycle__control__pb2.ConfigureResponse.SerializeToString,
            ),
            'Activate': grpc.unary_unary_rpc_method_handler(
                    servicer.Activate,
                    request_deserializer=sil_dot_lifecycle__control__pb2.ActivateRequest.FromString,
                    response_serializer=sil_dot_lifecycle__control__pb2.ActivateResponse.SerializeToString,
            ),
            'Deactivate': grpc.unary_unary_rpc_method_handler(
                    servicer.Deactivate,
                    request_deserializer=sil_dot_lifecycle__control__pb2.DeactivateRequest.FromString,
                    response_serializer=sil_dot_lifecycle__control__pb2.DeactivateResponse.SerializeToString,
            ),
            'Cleanup': grpc.unary_unary_rpc_method_handler(
                    servicer.Cleanup,
                    request_deserializer=sil_dot_lifecycle__control__pb2.CleanupRequest.FromString,
                    response_serializer=sil_dot_lifecycle__control__pb2.CleanupResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sil.LifecycleControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sil.LifecycleControlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LifecycleControlService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Configure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sil.LifecycleControlService/Configure',
            sil_dot_lifecycle__control__pb2.ConfigureRequest.SerializeToString,
            sil_dot_lifecycle__control__pb2.ConfigureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Activate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sil.LifecycleControlService/Activate',
            sil_dot_lifecycle__control__pb2.ActivateRequest.SerializeToString,
            sil_dot_lifecycle__control__pb2.ActivateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Deactivate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sil.LifecycleControlService/Deactivate',
            sil_dot_lifecycle__control__pb2.DeactivateRequest.SerializeToString,
            sil_dot_lifecycle__control__pb2.DeactivateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Cleanup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sil.LifecycleControlService/Cleanup',
            sil_dot_lifecycle__control__pb2.CleanupRequest.SerializeToString,
            sil_dot_lifecycle__control__pb2.CleanupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
