# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sil/lifecycle_control.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sil/lifecycle_control.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bsil/lifecycle_control.proto\x12\x03sil\"\'\n\x10\x43onfigureRequest\x12\x13\n\x0bscenario_id\x18\x01 \x01(\t\"3\n\x11\x43onfigureResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"\x11\n\x0f\x41\x63tivateRequest\"2\n\x10\x41\x63tivateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"\x13\n\x11\x44\x65\x61\x63tivateRequest\"4\n\x12\x44\x65\x61\x63tivateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"\x10\n\x0e\x43leanupRequest\"1\n\x0f\x43leanupResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t2\x83\x02\n\x17LifecycleControlService\x12:\n\tConfigure\x12\x15.sil.ConfigureRequest\x1a\x16.sil.ConfigureResponse\x12\x37\n\x08\x41\x63tivate\x12\x14.sil.ActivateRequest\x1a\x15.sil.ActivateResponse\x12=\n\nDeactivate\x12\x16.sil.DeactivateRequest\x1a\x17.sil.DeactivateResponse\x12\x34\n\x07\x43leanup\x12\x13.sil.CleanupRequest\x1a\x14.sil.CleanupResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sil.lifecycle_control_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONFIGUREREQUEST']._serialized_start=36
  _globals['_CONFIGUREREQUEST']._serialized_end=75
  _globals['_CONFIGURERESPONSE']._serialized_start=77
  _globals['_CONFIGURERESPONSE']._serialized_end=128
  _globals['_ACTIVATEREQUEST']._serialized_start=130
  _globals['_ACTIVATEREQUEST']._serialized_end=147
  _globals['_ACTIVATERESPONSE']._serialized_start=149
  _globals['_ACTIVATERESPONSE']._serialized_end=199
  _globals['_DEACTIVATEREQUEST']._serialized_start=201
  _globals['_DEACTIVATEREQUEST']._serialized_end=220
  _globals['_DEACTIVATERESPONSE']._serialized_start=222
  _globals['_DEACTIVATERESPONSE']._serialized_end=274
  _globals['_CLEANUPREQUEST']._serialized_start=276
  _globals['_CLEANUPREQUEST']._serialized_end=292
  _globals['_CLEANUPRESPONSE']._serialized_start=294
  _globals['_CLEANUPRESPONSE']._serialized_end=343
  _globals['_LIFECYCLECONTROLSERVICE']._serialized_start=346
  _globals['_LIFECYCLECONTROLSERVICE']._serialized_end=605
# @@protoc_insertion_point(module_scope)
