# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sil/lifecycle_status.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sil/lifecycle_status.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1asil/lifecycle_status.proto\x12\x03sil\x1a\x1fgoogle/protobuf/timestamp.proto\"\xac\x03\n\x0fLifecycleStatus\x12)\n\x05stamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12:\n\rcurrent_state\x18\x02 \x01(\x0e\x32#.sil.LifecycleStatus.LifecycleState\x12\x13\n\x0bscenario_id\x18\x03 \x01(\t\x12\x15\n\rscenario_hash\x18\x04 \x01(\t\x12\x10\n\x08sim_time\x18\x05 \x01(\x01\x12\x11\n\twall_time\x18\x06 \x01(\x01\x12\x10\n\x08sim_rate\x18\x07 \x01(\x01\"\xce\x01\n\x0eLifecycleState\x12\x1f\n\x1bLIFECYCLE_STATE_UNSPECIFIED\x10\x00\x12 \n\x1cLIFECYCLE_STATE_UNCONFIGURED\x10\x01\x12\x1c\n\x18LIFECYCLE_STATE_INACTIVE\x10\x02\x12\x1a\n\x16LIFECYCLE_STATE_ACTIVE\x10\x03\x12 \n\x1cLIFECYCLE_STATE_DEACTIVATING\x10\x04\x12\x1d\n\x19LIFECYCLE_STATE_FINALIZED\x10\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sil.lifecycle_status_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LIFECYCLESTATUS']._serialized_start=69
  _globals['_LIFECYCLESTATUS']._serialized_end=497
  _globals['_LIFECYCLESTATUS_LIFECYCLESTATE']._serialized_start=291
  _globals['_LIFECYCLESTATUS_LIFECYCLESTATE']._serialized_end=497
# @@protoc_insertion_point(module_scope)
