# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sil/module_pulse.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sil/module_pulse.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16sil/module_pulse.proto\x12\x03sil\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe9\x03\n\x0bModulePulse\x12)\n\x05stamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12,\n\tmodule_id\x18\x02 \x01(\x0e\x32\x19.sil.ModulePulse.ModuleId\x12+\n\x05state\x18\x03 \x01(\x0e\x32\x1c.sil.ModulePulse.HealthState\x12\x12\n\nlatency_ms\x18\x04 \x01(\r\x12\x15\n\rmessage_drops\x18\x05 \x01(\r\"\xb5\x01\n\x08ModuleId\x12\x19\n\x15MODULE_ID_UNSPECIFIED\x10\x00\x12\x10\n\x0cMODULE_ID_M1\x10\x01\x12\x10\n\x0cMODULE_ID_M2\x10\x02\x12\x10\n\x0cMODULE_ID_M3\x10\x03\x12\x10\n\x0cMODULE_ID_M4\x10\x04\x12\x10\n\x0cMODULE_ID_M5\x10\x05\x12\x10\n\x0cMODULE_ID_M6\x10\x06\x12\x10\n\x0cMODULE_ID_M7\x10\x07\x12\x10\n\x0cMODULE_ID_M8\x10\x08\"q\n\x0bHealthState\x12\x1c\n\x18HEALTH_STATE_UNSPECIFIED\x10\x00\x12\x16\n\x12HEALTH_STATE_GREEN\x10\x01\x12\x16\n\x12HEALTH_STATE_AMBER\x10\x02\x12\x14\n\x10HEALTH_STATE_RED\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sil.module_pulse_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MODULEPULSE']._serialized_start=65
  _globals['_MODULEPULSE']._serialized_end=554
  _globals['_MODULEPULSE_MODULEID']._serialized_start=258
  _globals['_MODULEPULSE_MODULEID']._serialized_end=439
  _globals['_MODULEPULSE_HEALTHSTATE']._serialized_start=441
  _globals['_MODULEPULSE_HEALTHSTATE']._serialized_end=554
# @@protoc_insertion_point(module_scope)
