# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sil/own_ship_state.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sil/own_ship_state.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18sil/own_ship_state.proto\x12\x03sil\x1a\x1fgoogle/protobuf/timestamp.proto\"\x89\x03\n\x0cOwnShipState\x12)\n\x05stamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12$\n\x04pose\x18\x02 \x01(\x0b\x32\x16.sil.OwnShipState.Pose\x12\x30\n\nkinematics\x18\x03 \x01(\x0b\x32\x1c.sil.OwnShipState.Kinematics\x12\x35\n\rcontrol_state\x18\x04 \x01(\x0b\x32\x1e.sil.OwnShipState.ControlState\x1a\x31\n\x04Pose\x12\x0b\n\x03lat\x18\x01 \x01(\x01\x12\x0b\n\x03lon\x18\x02 \x01(\x01\x12\x0f\n\x07heading\x18\x03 \x01(\x01\x1aT\n\nKinematics\x12\x0b\n\x03sog\x18\x01 \x01(\x01\x12\x0b\n\x03\x63og\x18\x02 \x01(\x01\x12\x0b\n\x03rot\x18\x03 \x01(\x01\x12\t\n\x01u\x18\x04 \x01(\x01\x12\t\n\x01v\x18\x05 \x01(\x01\x12\t\n\x01r\x18\x06 \x01(\x01\x1a\x36\n\x0c\x43ontrolState\x12\x14\n\x0crudder_angle\x18\x01 \x01(\x01\x12\x10\n\x08throttle\x18\x02 \x01(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sil.own_ship_state_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OWNSHIPSTATE']._serialized_start=67
  _globals['_OWNSHIPSTATE']._serialized_end=460
  _globals['_OWNSHIPSTATE_POSE']._serialized_start=269
  _globals['_OWNSHIPSTATE_POSE']._serialized_end=318
  _globals['_OWNSHIPSTATE_KINEMATICS']._serialized_start=320
  _globals['_OWNSHIPSTATE_KINEMATICS']._serialized_end=404
  _globals['_OWNSHIPSTATE_CONTROLSTATE']._serialized_start=406
  _globals['_OWNSHIPSTATE_CONTROLSTATE']._serialized_end=460
# @@protoc_insertion_point(module_scope)
