# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sil/radar_measurement.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sil/radar_measurement.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bsil/radar_measurement.proto\x12\x03sil\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd0\x01\n\x10RadarMeasurement\x12)\n\x05stamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x38\n\rpolar_targets\x18\x02 \x03(\x0b\x32!.sil.RadarMeasurement.PolarTarget\x12\x1b\n\x13\x63lutter_cardinality\x18\x03 \x01(\r\x1a:\n\x0bPolarTarget\x12\r\n\x05range\x18\x01 \x01(\x01\x12\x0f\n\x07\x62\x65\x61ring\x18\x02 \x01(\x01\x12\x0b\n\x03rcs\x18\x03 \x01(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sil.radar_measurement_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RADARMEASUREMENT']._serialized_start=70
  _globals['_RADARMEASUREMENT']._serialized_end=278
  _globals['_RADARMEASUREMENT_POLARTARGET']._serialized_start=220
  _globals['_RADARMEASUREMENT_POLARTARGET']._serialized_end=278
# @@protoc_insertion_point(module_scope)
