# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sil/scenario_crud.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sil/scenario_crud.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17sil/scenario_crud.proto\x12\x03sil\"\r\n\x0bListRequest\"7\n\x0cListResponse\x12\'\n\tscenarios\x18\x01 \x03(\x0b\x32\x14.sil.ScenarioSummary\"C\n\x0fScenarioSummary\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x16\n\x0e\x65ncounter_type\x18\x03 \x01(\t\"!\n\nGetRequest\x12\x13\n\x0bscenario_id\x18\x01 \x01(\t\"1\n\x0bGetResponse\x12\x14\n\x0cyaml_content\x18\x01 \x01(\t\x12\x0c\n\x04hash\x18\x02 \x01(\t\"%\n\rCreateRequest\x12\x14\n\x0cyaml_content\x18\x01 \x01(\t\"3\n\x0e\x43reateResponse\x12\x13\n\x0bscenario_id\x18\x01 \x01(\t\x12\x0c\n\x04hash\x18\x02 \x01(\t\":\n\rUpdateRequest\x12\x13\n\x0bscenario_id\x18\x01 \x01(\t\x12\x14\n\x0cyaml_content\x18\x02 \x01(\t\"\x1e\n\x0eUpdateResponse\x12\x0c\n\x04hash\x18\x01 \x01(\t\"$\n\rDeleteRequest\x12\x13\n\x0bscenario_id\x18\x01 \x01(\t\"\x10\n\x0e\x44\x65leteResponse\"\'\n\x0fValidateRequest\x12\x14\n\x0cyaml_content\x18\x01 \x01(\t\"1\n\x10ValidateResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x0e\n\x06\x65rrors\x18\x02 \x03(\t2\xbe\x02\n\x13ScenarioCRUDService\x12+\n\x04List\x12\x10.sil.ListRequest\x1a\x11.sil.ListResponse\x12(\n\x03Get\x12\x0f.sil.GetRequest\x1a\x10.sil.GetResponse\x12\x31\n\x06\x43reate\x12\x12.sil.CreateRequest\x1a\x13.sil.CreateResponse\x12\x31\n\x06Update\x12\x12.sil.UpdateRequest\x1a\x13.sil.UpdateResponse\x12\x31\n\x06\x44\x65lete\x12\x12.sil.DeleteRequest\x1a\x13.sil.DeleteResponse\x12\x37\n\x08Validate\x12\x14.sil.ValidateRequest\x1a\x15.sil.ValidateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sil.scenario_crud_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LISTREQUEST']._serialized_start=32
  _globals['_LISTREQUEST']._serialized_end=45
  _globals['_LISTRESPONSE']._serialized_start=47
  _globals['_LISTRESPONSE']._serialized_end=102
  _globals['_SCENARIOSUMMARY']._serialized_start=104
  _globals['_SCENARIOSUMMARY']._serialized_end=171
  _globals['_GETREQUEST']._serialized_start=173
  _globals['_GETREQUEST']._serialized_end=206
  _globals['_GETRESPONSE']._serialized_start=208
  _globals['_GETRESPONSE']._serialized_end=257
  _globals['_CREATEREQUEST']._serialized_start=259
  _globals['_CREATEREQUEST']._serialized_end=296
  _globals['_CREATERESPONSE']._serialized_start=298
  _globals['_CREATERESPONSE']._serialized_end=349
  _globals['_UPDATEREQUEST']._serialized_start=351
  _globals['_UPDATEREQUEST']._serialized_end=409
  _globals['_UPDATERESPONSE']._serialized_start=411
  _globals['_UPDATERESPONSE']._serialized_end=441
  _globals['_DELETEREQUEST']._serialized_start=443
  _globals['_DELETEREQUEST']._serialized_end=479
  _globals['_DELETERESPONSE']._serialized_start=481
  _globals['_DELETERESPONSE']._serialized_end=497
  _globals['_VALIDATEREQUEST']._serialized_start=499
  _globals['_VALIDATEREQUEST']._serialized_end=538
  _globals['_VALIDATERESPONSE']._serialized_start=540
  _globals['_VALIDATERESPONSE']._serialized_end=589
  _globals['_SCENARIOCRUDSERVICE']._serialized_start=592
  _globals['_SCENARIOCRUDSERVICE']._serialized_end=910
# @@protoc_insertion_point(module_scope)
