# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sil/scoring_row.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sil/scoring_row.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15sil/scoring_row.proto\x12\x03sil\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb6\x01\n\nScoringRow\x12)\n\x05stamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0e\n\x06safety\x18\x02 \x01(\x01\x12\x17\n\x0frule_compliance\x18\x03 \x01(\x01\x12\r\n\x05\x64\x65lay\x18\x04 \x01(\x01\x12\x11\n\tmagnitude\x18\x05 \x01(\x01\x12\r\n\x05phase\x18\x06 \x01(\x01\x12\x14\n\x0cplausibility\x18\x07 \x01(\x01\x12\r\n\x05total\x18\x08 \x01(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sil.scoring_row_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCORINGROW']._serialized_start=64
  _globals['_SCORINGROW']._serialized_end=246
# @@protoc_insertion_point(module_scope)
