# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sil/self_check.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sil/self_check.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import module_pulse_pb2 as sil_dot_module__pulse__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14sil/self_check.proto\x12\x03sil\x1a\x16sil/module_pulse.proto\"\x0e\n\x0cProbeRequest\"A\n\rProbeResponse\x12\x11\n\tall_clear\x18\x01 \x01(\x08\x12\x1d\n\x05items\x18\x02 \x03(\x0b\x32\x0e.sil.CheckItem\"9\n\tCheckItem\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06passed\x18\x02 \x01(\x08\x12\x0e\n\x06\x64\x65tail\x18\x03 \x01(\t\"\x0f\n\rStatusRequest\"9\n\x0eStatusResponse\x12\'\n\rmodule_pulses\x18\x01 \x03(\x0b\x32\x10.sil.ModulePulse2u\n\x10SelfCheckService\x12.\n\x05Probe\x12\x11.sil.ProbeRequest\x1a\x12.sil.ProbeResponse\x12\x31\n\x06Status\x12\x12.sil.StatusRequest\x1a\x13.sil.StatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sil.self_check_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROBEREQUEST']._serialized_start=53
  _globals['_PROBEREQUEST']._serialized_end=67
  _globals['_PROBERESPONSE']._serialized_start=69
  _globals['_PROBERESPONSE']._serialized_end=134
  _globals['_CHECKITEM']._serialized_start=136
  _globals['_CHECKITEM']._serialized_end=193
  _globals['_STATUSREQUEST']._serialized_start=195
  _globals['_STATUSREQUEST']._serialized_end=210
  _globals['_STATUSRESPONSE']._serialized_start=212
  _globals['_STATUSRESPONSE']._serialized_end=269
  _globals['_SELFCHECKSERVICE']._serialized_start=271
  _globals['_SELFCHECKSERVICE']._serialized_end=388
# @@protoc_insertion_point(module_scope)
