# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import self_check_pb2 as sil_dot_self__check__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sil/self_check_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SelfCheckServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Probe = channel.unary_unary(
                '/sil.SelfCheckService/Probe',
                request_serializer=sil_dot_self__check__pb2.ProbeRequest.SerializeToString,
                response_deserializer=sil_dot_self__check__pb2.ProbeResponse.FromString,
                _registered_method=True)
        self.Status = channel.unary_unary(
                '/sil.SelfCheckService/Status',
                request_serializer=sil_dot_self__check__pb2.StatusRequest.SerializeToString,
                response_deserializer=sil_dot_self__check__pb2.StatusResponse.FromString,
                _registered_method=True)


class SelfCheckServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Probe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SelfCheckServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Probe': grpc.unary_unary_rpc_method_handler(
                    servicer.Probe,
                    request_deserializer=sil_dot_self__check__pb2.ProbeRequest.FromString,
                    response_serializer=sil_dot_self__check__pb2.ProbeResponse.SerializeToString,
            ),
            'Status': grpc.unary_unary_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=sil_dot_self__check__pb2.StatusRequest.FromString,
                    response_serializer=sil_dot_self__check__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sil.SelfCheckService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sil.SelfCheckService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SelfCheckService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Probe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sil.SelfCheckService/Probe',
            sil_dot_self__check__pb2.ProbeRequest.SerializeToString,
            sil_dot_self__check__pb2.ProbeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sil.SelfCheckService/Status',
            sil_dot_self__check__pb2.StatusRequest.SerializeToString,
            sil_dot_self__check__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
