# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sil/sim_clock.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sil/sim_clock.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13sil/sim_clock.proto\x12\x03sil\"\x1e\n\x0eSetRateRequest\x12\x0c\n\x04rate\x18\x01 \x01(\x01\"\"\n\x0fSetRateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x10\n\x0eGetTimeRequest\"6\n\x0fGetTimeResponse\x12\x10\n\x08sim_time\x18\x01 \x01(\x01\x12\x11\n\twall_time\x18\x02 \x01(\x01\x32}\n\x0fSimClockService\x12\x34\n\x07SetRate\x12\x13.sil.SetRateRequest\x1a\x14.sil.SetRateResponse\x12\x34\n\x07GetTime\x12\x13.sil.GetTimeRequest\x1a\x14.sil.GetTimeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sil.sim_clock_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SETRATEREQUEST']._serialized_start=28
  _globals['_SETRATEREQUEST']._serialized_end=58
  _globals['_SETRATERESPONSE']._serialized_start=60
  _globals['_SETRATERESPONSE']._serialized_end=94
  _globals['_GETTIMEREQUEST']._serialized_start=96
  _globals['_GETTIMEREQUEST']._serialized_end=112
  _globals['_GETTIMERESPONSE']._serialized_start=114
  _globals['_GETTIMERESPONSE']._serialized_end=168
  _globals['_SIMCLOCKSERVICE']._serialized_start=170
  _globals['_SIMCLOCKSERVICE']._serialized_end=295
# @@protoc_insertion_point(module_scope)
