# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import sim_clock_pb2 as sil_dot_sim__clock__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sil/sim_clock_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SimClockServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetRate = channel.unary_unary(
                '/sil.SimClockService/SetRate',
                request_serializer=sil_dot_sim__clock__pb2.SetRateRequest.SerializeToString,
                response_deserializer=sil_dot_sim__clock__pb2.SetRateResponse.FromString,
                _registered_method=True)
        self.GetTime = channel.unary_unary(
                '/sil.SimClockService/GetTime',
                request_serializer=sil_dot_sim__clock__pb2.GetTimeRequest.SerializeToString,
                response_deserializer=sil_dot_sim__clock__pb2.GetTimeResponse.FromString,
                _registered_method=True)


class SimClockServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetRate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimClockServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetRate': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRate,
                    request_deserializer=sil_dot_sim__clock__pb2.SetRateRequest.FromString,
                    response_serializer=sil_dot_sim__clock__pb2.SetRateResponse.SerializeToString,
            ),
            'GetTime': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTime,
                    request_deserializer=sil_dot_sim__clock__pb2.GetTimeRequest.FromString,
                    response_serializer=sil_dot_sim__clock__pb2.GetTimeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sil.SimClockService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sil.SimClockService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SimClockService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetRate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sil.SimClockService/SetRate',
            sil_dot_sim__clock__pb2.SetRateRequest.SerializeToString,
            sil_dot_sim__clock__pb2.SetRateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sil.SimClockService/GetTime',
            sil_dot_sim__clock__pb2.GetTimeRequest.SerializeToString,
            sil_dot_sim__clock__pb2.GetTimeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
