# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sil/target_vessel_state.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sil/target_vessel_state.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dsil/target_vessel_state.proto\x12\x03sil\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9f\x05\n\x11TargetVesselState\x12)\n\x05stamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0c\n\x04mmsi\x18\x02 \x01(\r\x12)\n\x04pose\x18\x03 \x01(\x0b\x32\x1b.sil.TargetVesselState.Pose\x12\x35\n\nkinematics\x18\x04 \x01(\x0b\x32!.sil.TargetVesselState.Kinematics\x12\x32\n\tship_type\x18\x05 \x01(\x0e\x32\x1f.sil.TargetVesselState.ShipType\x12/\n\x04mode\x18\x06 \x01(\x0e\x32!.sil.TargetVesselState.TargetMode\x1a\x31\n\x04Pose\x12\x0b\n\x03lat\x18\x01 \x01(\x01\x12\x0b\n\x03lon\x18\x02 \x01(\x01\x12\x0f\n\x07heading\x18\x03 \x01(\x01\x1a\x33\n\nKinematics\x12\x0b\n\x03sog\x18\x01 \x01(\x01\x12\x0b\n\x03\x63og\x18\x02 \x01(\x01\x12\x0b\n\x03rot\x18\x03 \x01(\x01\"\xab\x01\n\x08ShipType\x12\x19\n\x15SHIP_TYPE_UNSPECIFIED\x10\x00\x12\x13\n\x0fSHIP_TYPE_CARGO\x10\x01\x12\x14\n\x10SHIP_TYPE_TANKER\x10\x02\x12\x17\n\x13SHIP_TYPE_PASSENGER\x10\x03\x12\x15\n\x11SHIP_TYPE_FISHING\x10\x04\x12\x11\n\rSHIP_TYPE_TUG\x10\x05\x12\x16\n\x12SHIP_TYPE_PLEASURE\x10\x06\"t\n\nTargetMode\x12\x1b\n\x17TARGET_MODE_UNSPECIFIED\x10\x00\x12\x16\n\x12TARGET_MODE_REPLAY\x10\x01\x12\x14\n\x10TARGET_MODE_NCDM\x10\x02\x12\x1b\n\x17TARGET_MODE_INTELLIGENT\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sil.target_vessel_state_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TARGETVESSELSTATE']._serialized_start=72
  _globals['_TARGETVESSELSTATE']._serialized_end=743
  _globals['_TARGETVESSELSTATE_POSE']._serialized_start=349
  _globals['_TARGETVESSELSTATE_POSE']._serialized_end=398
  _globals['_TARGETVESSELSTATE_KINEMATICS']._serialized_start=400
  _globals['_TARGETVESSELSTATE_KINEMATICS']._serialized_end=451
  _globals['_TARGETVESSELSTATE_SHIPTYPE']._serialized_start=454
  _globals['_TARGETVESSELSTATE_SHIPTYPE']._serialized_end=625
  _globals['_TARGETVESSELSTATE_TARGETMODE']._serialized_start=627
  _globals['_TARGETVESSELSTATE_TARGETMODE']._serialized_end=743
# @@protoc_insertion_point(module_scope)
