<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematyp="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>route_planning_ros2</name>
  <version>0.1.0</version>
  <description>Route planning bridge to GNC system (project1)</description>
  <maintainer email="qiao.huang@todo.todo">qiao.huang</maintainer>
  <license>Apache-2.0</license>
  <depend>rclpy</depend>
  <depend>nav_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>std_msgs</depend>
  <depend>ship_interfaces</depend>
  <buildtool_depend>ament_python</buildtool_depend>
  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
