#!/usr/bin/env bash
# Run from repo root on a host with Docker daemon access.
# Requires ros:jazzy-ros-base-noble to be already pulled.
# Output: version-lock.txt entries printed to stdout.
# Update flow: run this script -> review -> git commit version-lock.txt -> docker build
set -euo pipefail

IMAGE="ros:jazzy-ros-base-noble"

echo "# Auto-generated by audit-versions.sh — commit after review"
echo "# Update flow: run this script -> git commit version-lock.txt -> docker build"
echo ""

DIGEST=$(docker inspect "${IMAGE}" \
           --format='{{index .RepoDigests 0}}' 2>/dev/null | cut -d@ -f2 || echo "UNKNOWN")
echo "ROS_BASE_DIGEST=${DIGEST}"

docker run --rm "${IMAGE}" bash -c "
  export DEBIAN_FRONTEND=noninteractive
  apt-get update -qq 2>/dev/null
  for pkg in gcc-14 clang-tidy-20 cmake cppcheck python3.12; do
    ver=\$(apt-cache show \"\$pkg\" 2>/dev/null | grep '^Version:' | head -1 | awk '{print \$2}')
    varname=\$(echo \"\${pkg^^}_VER\" | sed 's/[-.]/_/g')
    echo \"\${varname}=\${ver}\"
  done
"
echo "# colcon-common-extensions: no PyPI release tag — known exception, not pinned"
